//
// GeneratedInt3Swizzles.h - generated-style public int3 swizzle declarations
//
// This file is generated by tools/gen_vector_swizzles.py.
// Do not hand-edit the swizzle list.
//

#pragma once

#define CHLM_DETAIL_DECLARE_INT3_SWIZZLES() \
    /* xyz family */ \
    /* xyz length 2 */ \
    detail::ivector_swizzle2<3, 0, 0> xx; \
    detail::ivector_swizzle2<3, 0, 1> xy; \
    detail::ivector_swizzle2<3, 0, 2> xz; \
    detail::ivector_swizzle2<3, 1, 0> yx; \
    detail::ivector_swizzle2<3, 1, 1> yy; \
    detail::ivector_swizzle2<3, 1, 2> yz; \
    detail::ivector_swizzle2<3, 2, 0> zx; \
    detail::ivector_swizzle2<3, 2, 1> zy; \
    detail::ivector_swizzle2<3, 2, 2> zz; \
    /* xyz length 3 */ \
    detail::ivector_swizzle3<3, 0, 0, 0> xxx; \
    detail::ivector_swizzle3<3, 0, 0, 1> xxy; \
    detail::ivector_swizzle3<3, 0, 0, 2> xxz; \
    detail::ivector_swizzle3<3, 0, 1, 0> xyx; \
    detail::ivector_swizzle3<3, 0, 1, 1> xyy; \
    detail::ivector_swizzle3<3, 0, 1, 2> xyz; \
    detail::ivector_swizzle3<3, 0, 2, 0> xzx; \
    detail::ivector_swizzle3<3, 0, 2, 1> xzy; \
    detail::ivector_swizzle3<3, 0, 2, 2> xzz; \
    detail::ivector_swizzle3<3, 1, 0, 0> yxx; \
    detail::ivector_swizzle3<3, 1, 0, 1> yxy; \
    detail::ivector_swizzle3<3, 1, 0, 2> yxz; \
    detail::ivector_swizzle3<3, 1, 1, 0> yyx; \
    detail::ivector_swizzle3<3, 1, 1, 1> yyy; \
    detail::ivector_swizzle3<3, 1, 1, 2> yyz; \
    detail::ivector_swizzle3<3, 1, 2, 0> yzx; \
    detail::ivector_swizzle3<3, 1, 2, 1> yzy; \
    detail::ivector_swizzle3<3, 1, 2, 2> yzz; \
    detail::ivector_swizzle3<3, 2, 0, 0> zxx; \
    detail::ivector_swizzle3<3, 2, 0, 1> zxy; \
    detail::ivector_swizzle3<3, 2, 0, 2> zxz; \
    detail::ivector_swizzle3<3, 2, 1, 0> zyx; \
    detail::ivector_swizzle3<3, 2, 1, 1> zyy; \
    detail::ivector_swizzle3<3, 2, 1, 2> zyz; \
    detail::ivector_swizzle3<3, 2, 2, 0> zzx; \
    detail::ivector_swizzle3<3, 2, 2, 1> zzy; \
    detail::ivector_swizzle3<3, 2, 2, 2> zzz; \
    /* xyz length 4 */ \
    detail::ivector_swizzle4<3, 0, 0, 0, 0> xxxx; \
    detail::ivector_swizzle4<3, 0, 0, 0, 1> xxxy; \
    detail::ivector_swizzle4<3, 0, 0, 0, 2> xxxz; \
    detail::ivector_swizzle4<3, 0, 0, 1, 0> xxyx; \
    detail::ivector_swizzle4<3, 0, 0, 1, 1> xxyy; \
    detail::ivector_swizzle4<3, 0, 0, 1, 2> xxyz; \
    detail::ivector_swizzle4<3, 0, 0, 2, 0> xxzx; \
    detail::ivector_swizzle4<3, 0, 0, 2, 1> xxzy; \
    detail::ivector_swizzle4<3, 0, 0, 2, 2> xxzz; \
    detail::ivector_swizzle4<3, 0, 1, 0, 0> xyxx; \
    detail::ivector_swizzle4<3, 0, 1, 0, 1> xyxy; \
    detail::ivector_swizzle4<3, 0, 1, 0, 2> xyxz; \
    detail::ivector_swizzle4<3, 0, 1, 1, 0> xyyx; \
    detail::ivector_swizzle4<3, 0, 1, 1, 1> xyyy; \
    detail::ivector_swizzle4<3, 0, 1, 1, 2> xyyz; \
    detail::ivector_swizzle4<3, 0, 1, 2, 0> xyzx; \
    detail::ivector_swizzle4<3, 0, 1, 2, 1> xyzy; \
    detail::ivector_swizzle4<3, 0, 1, 2, 2> xyzz; \
    detail::ivector_swizzle4<3, 0, 2, 0, 0> xzxx; \
    detail::ivector_swizzle4<3, 0, 2, 0, 1> xzxy; \
    detail::ivector_swizzle4<3, 0, 2, 0, 2> xzxz; \
    detail::ivector_swizzle4<3, 0, 2, 1, 0> xzyx; \
    detail::ivector_swizzle4<3, 0, 2, 1, 1> xzyy; \
    detail::ivector_swizzle4<3, 0, 2, 1, 2> xzyz; \
    detail::ivector_swizzle4<3, 0, 2, 2, 0> xzzx; \
    detail::ivector_swizzle4<3, 0, 2, 2, 1> xzzy; \
    detail::ivector_swizzle4<3, 0, 2, 2, 2> xzzz; \
    detail::ivector_swizzle4<3, 1, 0, 0, 0> yxxx; \
    detail::ivector_swizzle4<3, 1, 0, 0, 1> yxxy; \
    detail::ivector_swizzle4<3, 1, 0, 0, 2> yxxz; \
    detail::ivector_swizzle4<3, 1, 0, 1, 0> yxyx; \
    detail::ivector_swizzle4<3, 1, 0, 1, 1> yxyy; \
    detail::ivector_swizzle4<3, 1, 0, 1, 2> yxyz; \
    detail::ivector_swizzle4<3, 1, 0, 2, 0> yxzx; \
    detail::ivector_swizzle4<3, 1, 0, 2, 1> yxzy; \
    detail::ivector_swizzle4<3, 1, 0, 2, 2> yxzz; \
    detail::ivector_swizzle4<3, 1, 1, 0, 0> yyxx; \
    detail::ivector_swizzle4<3, 1, 1, 0, 1> yyxy; \
    detail::ivector_swizzle4<3, 1, 1, 0, 2> yyxz; \
    detail::ivector_swizzle4<3, 1, 1, 1, 0> yyyx; \
    detail::ivector_swizzle4<3, 1, 1, 1, 1> yyyy; \
    detail::ivector_swizzle4<3, 1, 1, 1, 2> yyyz; \
    detail::ivector_swizzle4<3, 1, 1, 2, 0> yyzx; \
    detail::ivector_swizzle4<3, 1, 1, 2, 1> yyzy; \
    detail::ivector_swizzle4<3, 1, 1, 2, 2> yyzz; \
    detail::ivector_swizzle4<3, 1, 2, 0, 0> yzxx; \
    detail::ivector_swizzle4<3, 1, 2, 0, 1> yzxy; \
    detail::ivector_swizzle4<3, 1, 2, 0, 2> yzxz; \
    detail::ivector_swizzle4<3, 1, 2, 1, 0> yzyx; \
    detail::ivector_swizzle4<3, 1, 2, 1, 1> yzyy; \
    detail::ivector_swizzle4<3, 1, 2, 1, 2> yzyz; \
    detail::ivector_swizzle4<3, 1, 2, 2, 0> yzzx; \
    detail::ivector_swizzle4<3, 1, 2, 2, 1> yzzy; \
    detail::ivector_swizzle4<3, 1, 2, 2, 2> yzzz; \
    detail::ivector_swizzle4<3, 2, 0, 0, 0> zxxx; \
    detail::ivector_swizzle4<3, 2, 0, 0, 1> zxxy; \
    detail::ivector_swizzle4<3, 2, 0, 0, 2> zxxz; \
    detail::ivector_swizzle4<3, 2, 0, 1, 0> zxyx; \
    detail::ivector_swizzle4<3, 2, 0, 1, 1> zxyy; \
    detail::ivector_swizzle4<3, 2, 0, 1, 2> zxyz; \
    detail::ivector_swizzle4<3, 2, 0, 2, 0> zxzx; \
    detail::ivector_swizzle4<3, 2, 0, 2, 1> zxzy; \
    detail::ivector_swizzle4<3, 2, 0, 2, 2> zxzz; \
    detail::ivector_swizzle4<3, 2, 1, 0, 0> zyxx; \
    detail::ivector_swizzle4<3, 2, 1, 0, 1> zyxy; \
    detail::ivector_swizzle4<3, 2, 1, 0, 2> zyxz; \
    detail::ivector_swizzle4<3, 2, 1, 1, 0> zyyx; \
    detail::ivector_swizzle4<3, 2, 1, 1, 1> zyyy; \
    detail::ivector_swizzle4<3, 2, 1, 1, 2> zyyz; \
    detail::ivector_swizzle4<3, 2, 1, 2, 0> zyzx; \
    detail::ivector_swizzle4<3, 2, 1, 2, 1> zyzy; \
    detail::ivector_swizzle4<3, 2, 1, 2, 2> zyzz; \
    detail::ivector_swizzle4<3, 2, 2, 0, 0> zzxx; \
    detail::ivector_swizzle4<3, 2, 2, 0, 1> zzxy; \
    detail::ivector_swizzle4<3, 2, 2, 0, 2> zzxz; \
    detail::ivector_swizzle4<3, 2, 2, 1, 0> zzyx; \
    detail::ivector_swizzle4<3, 2, 2, 1, 1> zzyy; \
    detail::ivector_swizzle4<3, 2, 2, 1, 2> zzyz; \
    detail::ivector_swizzle4<3, 2, 2, 2, 0> zzzx; \
    detail::ivector_swizzle4<3, 2, 2, 2, 1> zzzy; \
    detail::ivector_swizzle4<3, 2, 2, 2, 2> zzzz; \
    /* rgb family */ \
    /* rgb length 2 */ \
    detail::ivector_swizzle2<3, 0, 0> rr; \
    detail::ivector_swizzle2<3, 0, 1> rg; \
    detail::ivector_swizzle2<3, 0, 2> rb; \
    detail::ivector_swizzle2<3, 1, 0> gr; \
    detail::ivector_swizzle2<3, 1, 1> gg; \
    detail::ivector_swizzle2<3, 1, 2> gb; \
    detail::ivector_swizzle2<3, 2, 0> br; \
    detail::ivector_swizzle2<3, 2, 1> bg; \
    detail::ivector_swizzle2<3, 2, 2> bb; \
    /* rgb length 3 */ \
    detail::ivector_swizzle3<3, 0, 0, 0> rrr; \
    detail::ivector_swizzle3<3, 0, 0, 1> rrg; \
    detail::ivector_swizzle3<3, 0, 0, 2> rrb; \
    detail::ivector_swizzle3<3, 0, 1, 0> rgr; \
    detail::ivector_swizzle3<3, 0, 1, 1> rgg; \
    detail::ivector_swizzle3<3, 0, 1, 2> rgb; \
    detail::ivector_swizzle3<3, 0, 2, 0> rbr; \
    detail::ivector_swizzle3<3, 0, 2, 1> rbg; \
    detail::ivector_swizzle3<3, 0, 2, 2> rbb; \
    detail::ivector_swizzle3<3, 1, 0, 0> grr; \
    detail::ivector_swizzle3<3, 1, 0, 1> grg; \
    detail::ivector_swizzle3<3, 1, 0, 2> grb; \
    detail::ivector_swizzle3<3, 1, 1, 0> ggr; \
    detail::ivector_swizzle3<3, 1, 1, 1> ggg; \
    detail::ivector_swizzle3<3, 1, 1, 2> ggb; \
    detail::ivector_swizzle3<3, 1, 2, 0> gbr; \
    detail::ivector_swizzle3<3, 1, 2, 1> gbg; \
    detail::ivector_swizzle3<3, 1, 2, 2> gbb; \
    detail::ivector_swizzle3<3, 2, 0, 0> brr; \
    detail::ivector_swizzle3<3, 2, 0, 1> brg; \
    detail::ivector_swizzle3<3, 2, 0, 2> brb; \
    detail::ivector_swizzle3<3, 2, 1, 0> bgr; \
    detail::ivector_swizzle3<3, 2, 1, 1> bgg; \
    detail::ivector_swizzle3<3, 2, 1, 2> bgb; \
    detail::ivector_swizzle3<3, 2, 2, 0> bbr; \
    detail::ivector_swizzle3<3, 2, 2, 1> bbg; \
    detail::ivector_swizzle3<3, 2, 2, 2> bbb; \
    /* rgb length 4 */ \
    detail::ivector_swizzle4<3, 0, 0, 0, 0> rrrr; \
    detail::ivector_swizzle4<3, 0, 0, 0, 1> rrrg; \
    detail::ivector_swizzle4<3, 0, 0, 0, 2> rrrb; \
    detail::ivector_swizzle4<3, 0, 0, 1, 0> rrgr; \
    detail::ivector_swizzle4<3, 0, 0, 1, 1> rrgg; \
    detail::ivector_swizzle4<3, 0, 0, 1, 2> rrgb; \
    detail::ivector_swizzle4<3, 0, 0, 2, 0> rrbr; \
    detail::ivector_swizzle4<3, 0, 0, 2, 1> rrbg; \
    detail::ivector_swizzle4<3, 0, 0, 2, 2> rrbb; \
    detail::ivector_swizzle4<3, 0, 1, 0, 0> rgrr; \
    detail::ivector_swizzle4<3, 0, 1, 0, 1> rgrg; \
    detail::ivector_swizzle4<3, 0, 1, 0, 2> rgrb; \
    detail::ivector_swizzle4<3, 0, 1, 1, 0> rggr; \
    detail::ivector_swizzle4<3, 0, 1, 1, 1> rggg; \
    detail::ivector_swizzle4<3, 0, 1, 1, 2> rggb; \
    detail::ivector_swizzle4<3, 0, 1, 2, 0> rgbr; \
    detail::ivector_swizzle4<3, 0, 1, 2, 1> rgbg; \
    detail::ivector_swizzle4<3, 0, 1, 2, 2> rgbb; \
    detail::ivector_swizzle4<3, 0, 2, 0, 0> rbrr; \
    detail::ivector_swizzle4<3, 0, 2, 0, 1> rbrg; \
    detail::ivector_swizzle4<3, 0, 2, 0, 2> rbrb; \
    detail::ivector_swizzle4<3, 0, 2, 1, 0> rbgr; \
    detail::ivector_swizzle4<3, 0, 2, 1, 1> rbgg; \
    detail::ivector_swizzle4<3, 0, 2, 1, 2> rbgb; \
    detail::ivector_swizzle4<3, 0, 2, 2, 0> rbbr; \
    detail::ivector_swizzle4<3, 0, 2, 2, 1> rbbg; \
    detail::ivector_swizzle4<3, 0, 2, 2, 2> rbbb; \
    detail::ivector_swizzle4<3, 1, 0, 0, 0> grrr; \
    detail::ivector_swizzle4<3, 1, 0, 0, 1> grrg; \
    detail::ivector_swizzle4<3, 1, 0, 0, 2> grrb; \
    detail::ivector_swizzle4<3, 1, 0, 1, 0> grgr; \
    detail::ivector_swizzle4<3, 1, 0, 1, 1> grgg; \
    detail::ivector_swizzle4<3, 1, 0, 1, 2> grgb; \
    detail::ivector_swizzle4<3, 1, 0, 2, 0> grbr; \
    detail::ivector_swizzle4<3, 1, 0, 2, 1> grbg; \
    detail::ivector_swizzle4<3, 1, 0, 2, 2> grbb; \
    detail::ivector_swizzle4<3, 1, 1, 0, 0> ggrr; \
    detail::ivector_swizzle4<3, 1, 1, 0, 1> ggrg; \
    detail::ivector_swizzle4<3, 1, 1, 0, 2> ggrb; \
    detail::ivector_swizzle4<3, 1, 1, 1, 0> gggr; \
    detail::ivector_swizzle4<3, 1, 1, 1, 1> gggg; \
    detail::ivector_swizzle4<3, 1, 1, 1, 2> gggb; \
    detail::ivector_swizzle4<3, 1, 1, 2, 0> ggbr; \
    detail::ivector_swizzle4<3, 1, 1, 2, 1> ggbg; \
    detail::ivector_swizzle4<3, 1, 1, 2, 2> ggbb; \
    detail::ivector_swizzle4<3, 1, 2, 0, 0> gbrr; \
    detail::ivector_swizzle4<3, 1, 2, 0, 1> gbrg; \
    detail::ivector_swizzle4<3, 1, 2, 0, 2> gbrb; \
    detail::ivector_swizzle4<3, 1, 2, 1, 0> gbgr; \
    detail::ivector_swizzle4<3, 1, 2, 1, 1> gbgg; \
    detail::ivector_swizzle4<3, 1, 2, 1, 2> gbgb; \
    detail::ivector_swizzle4<3, 1, 2, 2, 0> gbbr; \
    detail::ivector_swizzle4<3, 1, 2, 2, 1> gbbg; \
    detail::ivector_swizzle4<3, 1, 2, 2, 2> gbbb; \
    detail::ivector_swizzle4<3, 2, 0, 0, 0> brrr; \
    detail::ivector_swizzle4<3, 2, 0, 0, 1> brrg; \
    detail::ivector_swizzle4<3, 2, 0, 0, 2> brrb; \
    detail::ivector_swizzle4<3, 2, 0, 1, 0> brgr; \
    detail::ivector_swizzle4<3, 2, 0, 1, 1> brgg; \
    detail::ivector_swizzle4<3, 2, 0, 1, 2> brgb; \
    detail::ivector_swizzle4<3, 2, 0, 2, 0> brbr; \
    detail::ivector_swizzle4<3, 2, 0, 2, 1> brbg; \
    detail::ivector_swizzle4<3, 2, 0, 2, 2> brbb; \
    detail::ivector_swizzle4<3, 2, 1, 0, 0> bgrr; \
    detail::ivector_swizzle4<3, 2, 1, 0, 1> bgrg; \
    detail::ivector_swizzle4<3, 2, 1, 0, 2> bgrb; \
    detail::ivector_swizzle4<3, 2, 1, 1, 0> bggr; \
    detail::ivector_swizzle4<3, 2, 1, 1, 1> bggg; \
    detail::ivector_swizzle4<3, 2, 1, 1, 2> bggb; \
    detail::ivector_swizzle4<3, 2, 1, 2, 0> bgbr; \
    detail::ivector_swizzle4<3, 2, 1, 2, 1> bgbg; \
    detail::ivector_swizzle4<3, 2, 1, 2, 2> bgbb; \
    detail::ivector_swizzle4<3, 2, 2, 0, 0> bbrr; \
    detail::ivector_swizzle4<3, 2, 2, 0, 1> bbrg; \
    detail::ivector_swizzle4<3, 2, 2, 0, 2> bbrb; \
    detail::ivector_swizzle4<3, 2, 2, 1, 0> bbgr; \
    detail::ivector_swizzle4<3, 2, 2, 1, 1> bbgg; \
    detail::ivector_swizzle4<3, 2, 2, 1, 2> bbgb; \
    detail::ivector_swizzle4<3, 2, 2, 2, 0> bbbr; \
    detail::ivector_swizzle4<3, 2, 2, 2, 1> bbbg; \
    detail::ivector_swizzle4<3, 2, 2, 2, 2> bbbb; \
    /* stp family */ \
    /* stp length 2 */ \
    detail::ivector_swizzle2<3, 0, 0> ss; \
    detail::ivector_swizzle2<3, 0, 1> st; \
    detail::ivector_swizzle2<3, 0, 2> sp; \
    detail::ivector_swizzle2<3, 1, 0> ts; \
    detail::ivector_swizzle2<3, 1, 1> tt; \
    detail::ivector_swizzle2<3, 1, 2> tp; \
    detail::ivector_swizzle2<3, 2, 0> ps; \
    detail::ivector_swizzle2<3, 2, 1> pt; \
    detail::ivector_swizzle2<3, 2, 2> pp; \
    /* stp length 3 */ \
    detail::ivector_swizzle3<3, 0, 0, 0> sss; \
    detail::ivector_swizzle3<3, 0, 0, 1> sst; \
    detail::ivector_swizzle3<3, 0, 0, 2> ssp; \
    detail::ivector_swizzle3<3, 0, 1, 0> sts; \
    detail::ivector_swizzle3<3, 0, 1, 1> stt; \
    detail::ivector_swizzle3<3, 0, 1, 2> stp; \
    detail::ivector_swizzle3<3, 0, 2, 0> sps; \
    detail::ivector_swizzle3<3, 0, 2, 1> spt; \
    detail::ivector_swizzle3<3, 0, 2, 2> spp; \
    detail::ivector_swizzle3<3, 1, 0, 0> tss; \
    detail::ivector_swizzle3<3, 1, 0, 1> tst; \
    detail::ivector_swizzle3<3, 1, 0, 2> tsp; \
    detail::ivector_swizzle3<3, 1, 1, 0> tts; \
    detail::ivector_swizzle3<3, 1, 1, 1> ttt; \
    detail::ivector_swizzle3<3, 1, 1, 2> ttp; \
    detail::ivector_swizzle3<3, 1, 2, 0> tps; \
    detail::ivector_swizzle3<3, 1, 2, 1> tpt; \
    detail::ivector_swizzle3<3, 1, 2, 2> tpp; \
    detail::ivector_swizzle3<3, 2, 0, 0> pss; \
    detail::ivector_swizzle3<3, 2, 0, 1> pst; \
    detail::ivector_swizzle3<3, 2, 0, 2> psp; \
    detail::ivector_swizzle3<3, 2, 1, 0> pts; \
    detail::ivector_swizzle3<3, 2, 1, 1> ptt; \
    detail::ivector_swizzle3<3, 2, 1, 2> ptp; \
    detail::ivector_swizzle3<3, 2, 2, 0> pps; \
    detail::ivector_swizzle3<3, 2, 2, 1> ppt; \
    detail::ivector_swizzle3<3, 2, 2, 2> ppp; \
    /* stp length 4 */ \
    detail::ivector_swizzle4<3, 0, 0, 0, 0> ssss; \
    detail::ivector_swizzle4<3, 0, 0, 0, 1> ssst; \
    detail::ivector_swizzle4<3, 0, 0, 0, 2> sssp; \
    detail::ivector_swizzle4<3, 0, 0, 1, 0> ssts; \
    detail::ivector_swizzle4<3, 0, 0, 1, 1> sstt; \
    detail::ivector_swizzle4<3, 0, 0, 1, 2> sstp; \
    detail::ivector_swizzle4<3, 0, 0, 2, 0> ssps; \
    detail::ivector_swizzle4<3, 0, 0, 2, 1> sspt; \
    detail::ivector_swizzle4<3, 0, 0, 2, 2> sspp; \
    detail::ivector_swizzle4<3, 0, 1, 0, 0> stss; \
    detail::ivector_swizzle4<3, 0, 1, 0, 1> stst; \
    detail::ivector_swizzle4<3, 0, 1, 0, 2> stsp; \
    detail::ivector_swizzle4<3, 0, 1, 1, 0> stts; \
    detail::ivector_swizzle4<3, 0, 1, 1, 1> sttt; \
    detail::ivector_swizzle4<3, 0, 1, 1, 2> sttp; \
    detail::ivector_swizzle4<3, 0, 1, 2, 0> stps; \
    detail::ivector_swizzle4<3, 0, 1, 2, 1> stpt; \
    detail::ivector_swizzle4<3, 0, 1, 2, 2> stpp; \
    detail::ivector_swizzle4<3, 0, 2, 0, 0> spss; \
    detail::ivector_swizzle4<3, 0, 2, 0, 1> spst; \
    detail::ivector_swizzle4<3, 0, 2, 0, 2> spsp; \
    detail::ivector_swizzle4<3, 0, 2, 1, 0> spts; \
    detail::ivector_swizzle4<3, 0, 2, 1, 1> sptt; \
    detail::ivector_swizzle4<3, 0, 2, 1, 2> sptp; \
    detail::ivector_swizzle4<3, 0, 2, 2, 0> spps; \
    detail::ivector_swizzle4<3, 0, 2, 2, 1> sppt; \
    detail::ivector_swizzle4<3, 0, 2, 2, 2> sppp; \
    detail::ivector_swizzle4<3, 1, 0, 0, 0> tsss; \
    detail::ivector_swizzle4<3, 1, 0, 0, 1> tsst; \
    detail::ivector_swizzle4<3, 1, 0, 0, 2> tssp; \
    detail::ivector_swizzle4<3, 1, 0, 1, 0> tsts; \
    detail::ivector_swizzle4<3, 1, 0, 1, 1> tstt; \
    detail::ivector_swizzle4<3, 1, 0, 1, 2> tstp; \
    detail::ivector_swizzle4<3, 1, 0, 2, 0> tsps; \
    detail::ivector_swizzle4<3, 1, 0, 2, 1> tspt; \
    detail::ivector_swizzle4<3, 1, 0, 2, 2> tspp; \
    detail::ivector_swizzle4<3, 1, 1, 0, 0> ttss; \
    detail::ivector_swizzle4<3, 1, 1, 0, 1> ttst; \
    detail::ivector_swizzle4<3, 1, 1, 0, 2> ttsp; \
    detail::ivector_swizzle4<3, 1, 1, 1, 0> ttts; \
    detail::ivector_swizzle4<3, 1, 1, 1, 1> tttt; \
    detail::ivector_swizzle4<3, 1, 1, 1, 2> tttp; \
    detail::ivector_swizzle4<3, 1, 1, 2, 0> ttps; \
    detail::ivector_swizzle4<3, 1, 1, 2, 1> ttpt; \
    detail::ivector_swizzle4<3, 1, 1, 2, 2> ttpp; \
    detail::ivector_swizzle4<3, 1, 2, 0, 0> tpss; \
    detail::ivector_swizzle4<3, 1, 2, 0, 1> tpst; \
    detail::ivector_swizzle4<3, 1, 2, 0, 2> tpsp; \
    detail::ivector_swizzle4<3, 1, 2, 1, 0> tpts; \
    detail::ivector_swizzle4<3, 1, 2, 1, 1> tptt; \
    detail::ivector_swizzle4<3, 1, 2, 1, 2> tptp; \
    detail::ivector_swizzle4<3, 1, 2, 2, 0> tpps; \
    detail::ivector_swizzle4<3, 1, 2, 2, 1> tppt; \
    detail::ivector_swizzle4<3, 1, 2, 2, 2> tppp; \
    detail::ivector_swizzle4<3, 2, 0, 0, 0> psss; \
    detail::ivector_swizzle4<3, 2, 0, 0, 1> psst; \
    detail::ivector_swizzle4<3, 2, 0, 0, 2> pssp; \
    detail::ivector_swizzle4<3, 2, 0, 1, 0> psts; \
    detail::ivector_swizzle4<3, 2, 0, 1, 1> pstt; \
    detail::ivector_swizzle4<3, 2, 0, 1, 2> pstp; \
    detail::ivector_swizzle4<3, 2, 0, 2, 0> psps; \
    detail::ivector_swizzle4<3, 2, 0, 2, 1> pspt; \
    detail::ivector_swizzle4<3, 2, 0, 2, 2> pspp; \
    detail::ivector_swizzle4<3, 2, 1, 0, 0> ptss; \
    detail::ivector_swizzle4<3, 2, 1, 0, 1> ptst; \
    detail::ivector_swizzle4<3, 2, 1, 0, 2> ptsp; \
    detail::ivector_swizzle4<3, 2, 1, 1, 0> ptts; \
    detail::ivector_swizzle4<3, 2, 1, 1, 1> pttt; \
    detail::ivector_swizzle4<3, 2, 1, 1, 2> pttp; \
    detail::ivector_swizzle4<3, 2, 1, 2, 0> ptps; \
    detail::ivector_swizzle4<3, 2, 1, 2, 1> ptpt; \
    detail::ivector_swizzle4<3, 2, 1, 2, 2> ptpp; \
    detail::ivector_swizzle4<3, 2, 2, 0, 0> ppss; \
    detail::ivector_swizzle4<3, 2, 2, 0, 1> ppst; \
    detail::ivector_swizzle4<3, 2, 2, 0, 2> ppsp; \
    detail::ivector_swizzle4<3, 2, 2, 1, 0> ppts; \
    detail::ivector_swizzle4<3, 2, 2, 1, 1> pptt; \
    detail::ivector_swizzle4<3, 2, 2, 1, 2> pptp; \
    detail::ivector_swizzle4<3, 2, 2, 2, 0> ppps; \
    detail::ivector_swizzle4<3, 2, 2, 2, 1> pppt; \
    detail::ivector_swizzle4<3, 2, 2, 2, 2> pppp; \
    /* end generated int3 swizzles */
