//
// GeneratedInt4Swizzles.h - generated-style public int4 swizzle declarations
//
// This file is generated by tools/gen_vector_swizzles.py.
// Do not hand-edit the swizzle list.
//

#pragma once

#define CHLM_DETAIL_DECLARE_INT4_SWIZZLES() \
    /* xyzw family */ \
    /* xyzw length 2 */ \
    detail::ivector_swizzle2<4, 0, 0> xx; \
    detail::ivector_swizzle2<4, 0, 1> xy; \
    detail::ivector_swizzle2<4, 0, 2> xz; \
    detail::ivector_swizzle2<4, 0, 3> xw; \
    detail::ivector_swizzle2<4, 1, 0> yx; \
    detail::ivector_swizzle2<4, 1, 1> yy; \
    detail::ivector_swizzle2<4, 1, 2> yz; \
    detail::ivector_swizzle2<4, 1, 3> yw; \
    detail::ivector_swizzle2<4, 2, 0> zx; \
    detail::ivector_swizzle2<4, 2, 1> zy; \
    detail::ivector_swizzle2<4, 2, 2> zz; \
    detail::ivector_swizzle2<4, 2, 3> zw; \
    detail::ivector_swizzle2<4, 3, 0> wx; \
    detail::ivector_swizzle2<4, 3, 1> wy; \
    detail::ivector_swizzle2<4, 3, 2> wz; \
    detail::ivector_swizzle2<4, 3, 3> ww; \
    /* xyzw length 3 */ \
    detail::ivector_swizzle3<4, 0, 0, 0> xxx; \
    detail::ivector_swizzle3<4, 0, 0, 1> xxy; \
    detail::ivector_swizzle3<4, 0, 0, 2> xxz; \
    detail::ivector_swizzle3<4, 0, 0, 3> xxw; \
    detail::ivector_swizzle3<4, 0, 1, 0> xyx; \
    detail::ivector_swizzle3<4, 0, 1, 1> xyy; \
    detail::ivector_swizzle3<4, 0, 1, 2> xyz; \
    detail::ivector_swizzle3<4, 0, 1, 3> xyw; \
    detail::ivector_swizzle3<4, 0, 2, 0> xzx; \
    detail::ivector_swizzle3<4, 0, 2, 1> xzy; \
    detail::ivector_swizzle3<4, 0, 2, 2> xzz; \
    detail::ivector_swizzle3<4, 0, 2, 3> xzw; \
    detail::ivector_swizzle3<4, 0, 3, 0> xwx; \
    detail::ivector_swizzle3<4, 0, 3, 1> xwy; \
    detail::ivector_swizzle3<4, 0, 3, 2> xwz; \
    detail::ivector_swizzle3<4, 0, 3, 3> xww; \
    detail::ivector_swizzle3<4, 1, 0, 0> yxx; \
    detail::ivector_swizzle3<4, 1, 0, 1> yxy; \
    detail::ivector_swizzle3<4, 1, 0, 2> yxz; \
    detail::ivector_swizzle3<4, 1, 0, 3> yxw; \
    detail::ivector_swizzle3<4, 1, 1, 0> yyx; \
    detail::ivector_swizzle3<4, 1, 1, 1> yyy; \
    detail::ivector_swizzle3<4, 1, 1, 2> yyz; \
    detail::ivector_swizzle3<4, 1, 1, 3> yyw; \
    detail::ivector_swizzle3<4, 1, 2, 0> yzx; \
    detail::ivector_swizzle3<4, 1, 2, 1> yzy; \
    detail::ivector_swizzle3<4, 1, 2, 2> yzz; \
    detail::ivector_swizzle3<4, 1, 2, 3> yzw; \
    detail::ivector_swizzle3<4, 1, 3, 0> ywx; \
    detail::ivector_swizzle3<4, 1, 3, 1> ywy; \
    detail::ivector_swizzle3<4, 1, 3, 2> ywz; \
    detail::ivector_swizzle3<4, 1, 3, 3> yww; \
    detail::ivector_swizzle3<4, 2, 0, 0> zxx; \
    detail::ivector_swizzle3<4, 2, 0, 1> zxy; \
    detail::ivector_swizzle3<4, 2, 0, 2> zxz; \
    detail::ivector_swizzle3<4, 2, 0, 3> zxw; \
    detail::ivector_swizzle3<4, 2, 1, 0> zyx; \
    detail::ivector_swizzle3<4, 2, 1, 1> zyy; \
    detail::ivector_swizzle3<4, 2, 1, 2> zyz; \
    detail::ivector_swizzle3<4, 2, 1, 3> zyw; \
    detail::ivector_swizzle3<4, 2, 2, 0> zzx; \
    detail::ivector_swizzle3<4, 2, 2, 1> zzy; \
    detail::ivector_swizzle3<4, 2, 2, 2> zzz; \
    detail::ivector_swizzle3<4, 2, 2, 3> zzw; \
    detail::ivector_swizzle3<4, 2, 3, 0> zwx; \
    detail::ivector_swizzle3<4, 2, 3, 1> zwy; \
    detail::ivector_swizzle3<4, 2, 3, 2> zwz; \
    detail::ivector_swizzle3<4, 2, 3, 3> zww; \
    detail::ivector_swizzle3<4, 3, 0, 0> wxx; \
    detail::ivector_swizzle3<4, 3, 0, 1> wxy; \
    detail::ivector_swizzle3<4, 3, 0, 2> wxz; \
    detail::ivector_swizzle3<4, 3, 0, 3> wxw; \
    detail::ivector_swizzle3<4, 3, 1, 0> wyx; \
    detail::ivector_swizzle3<4, 3, 1, 1> wyy; \
    detail::ivector_swizzle3<4, 3, 1, 2> wyz; \
    detail::ivector_swizzle3<4, 3, 1, 3> wyw; \
    detail::ivector_swizzle3<4, 3, 2, 0> wzx; \
    detail::ivector_swizzle3<4, 3, 2, 1> wzy; \
    detail::ivector_swizzle3<4, 3, 2, 2> wzz; \
    detail::ivector_swizzle3<4, 3, 2, 3> wzw; \
    detail::ivector_swizzle3<4, 3, 3, 0> wwx; \
    detail::ivector_swizzle3<4, 3, 3, 1> wwy; \
    detail::ivector_swizzle3<4, 3, 3, 2> wwz; \
    detail::ivector_swizzle3<4, 3, 3, 3> www; \
    /* xyzw length 4 */ \
    detail::ivector_swizzle4<4, 0, 0, 0, 0> xxxx; \
    detail::ivector_swizzle4<4, 0, 0, 0, 1> xxxy; \
    detail::ivector_swizzle4<4, 0, 0, 0, 2> xxxz; \
    detail::ivector_swizzle4<4, 0, 0, 0, 3> xxxw; \
    detail::ivector_swizzle4<4, 0, 0, 1, 0> xxyx; \
    detail::ivector_swizzle4<4, 0, 0, 1, 1> xxyy; \
    detail::ivector_swizzle4<4, 0, 0, 1, 2> xxyz; \
    detail::ivector_swizzle4<4, 0, 0, 1, 3> xxyw; \
    detail::ivector_swizzle4<4, 0, 0, 2, 0> xxzx; \
    detail::ivector_swizzle4<4, 0, 0, 2, 1> xxzy; \
    detail::ivector_swizzle4<4, 0, 0, 2, 2> xxzz; \
    detail::ivector_swizzle4<4, 0, 0, 2, 3> xxzw; \
    detail::ivector_swizzle4<4, 0, 0, 3, 0> xxwx; \
    detail::ivector_swizzle4<4, 0, 0, 3, 1> xxwy; \
    detail::ivector_swizzle4<4, 0, 0, 3, 2> xxwz; \
    detail::ivector_swizzle4<4, 0, 0, 3, 3> xxww; \
    detail::ivector_swizzle4<4, 0, 1, 0, 0> xyxx; \
    detail::ivector_swizzle4<4, 0, 1, 0, 1> xyxy; \
    detail::ivector_swizzle4<4, 0, 1, 0, 2> xyxz; \
    detail::ivector_swizzle4<4, 0, 1, 0, 3> xyxw; \
    detail::ivector_swizzle4<4, 0, 1, 1, 0> xyyx; \
    detail::ivector_swizzle4<4, 0, 1, 1, 1> xyyy; \
    detail::ivector_swizzle4<4, 0, 1, 1, 2> xyyz; \
    detail::ivector_swizzle4<4, 0, 1, 1, 3> xyyw; \
    detail::ivector_swizzle4<4, 0, 1, 2, 0> xyzx; \
    detail::ivector_swizzle4<4, 0, 1, 2, 1> xyzy; \
    detail::ivector_swizzle4<4, 0, 1, 2, 2> xyzz; \
    detail::ivector_swizzle4<4, 0, 1, 2, 3> xyzw; \
    detail::ivector_swizzle4<4, 0, 1, 3, 0> xywx; \
    detail::ivector_swizzle4<4, 0, 1, 3, 1> xywy; \
    detail::ivector_swizzle4<4, 0, 1, 3, 2> xywz; \
    detail::ivector_swizzle4<4, 0, 1, 3, 3> xyww; \
    detail::ivector_swizzle4<4, 0, 2, 0, 0> xzxx; \
    detail::ivector_swizzle4<4, 0, 2, 0, 1> xzxy; \
    detail::ivector_swizzle4<4, 0, 2, 0, 2> xzxz; \
    detail::ivector_swizzle4<4, 0, 2, 0, 3> xzxw; \
    detail::ivector_swizzle4<4, 0, 2, 1, 0> xzyx; \
    detail::ivector_swizzle4<4, 0, 2, 1, 1> xzyy; \
    detail::ivector_swizzle4<4, 0, 2, 1, 2> xzyz; \
    detail::ivector_swizzle4<4, 0, 2, 1, 3> xzyw; \
    detail::ivector_swizzle4<4, 0, 2, 2, 0> xzzx; \
    detail::ivector_swizzle4<4, 0, 2, 2, 1> xzzy; \
    detail::ivector_swizzle4<4, 0, 2, 2, 2> xzzz; \
    detail::ivector_swizzle4<4, 0, 2, 2, 3> xzzw; \
    detail::ivector_swizzle4<4, 0, 2, 3, 0> xzwx; \
    detail::ivector_swizzle4<4, 0, 2, 3, 1> xzwy; \
    detail::ivector_swizzle4<4, 0, 2, 3, 2> xzwz; \
    detail::ivector_swizzle4<4, 0, 2, 3, 3> xzww; \
    detail::ivector_swizzle4<4, 0, 3, 0, 0> xwxx; \
    detail::ivector_swizzle4<4, 0, 3, 0, 1> xwxy; \
    detail::ivector_swizzle4<4, 0, 3, 0, 2> xwxz; \
    detail::ivector_swizzle4<4, 0, 3, 0, 3> xwxw; \
    detail::ivector_swizzle4<4, 0, 3, 1, 0> xwyx; \
    detail::ivector_swizzle4<4, 0, 3, 1, 1> xwyy; \
    detail::ivector_swizzle4<4, 0, 3, 1, 2> xwyz; \
    detail::ivector_swizzle4<4, 0, 3, 1, 3> xwyw; \
    detail::ivector_swizzle4<4, 0, 3, 2, 0> xwzx; \
    detail::ivector_swizzle4<4, 0, 3, 2, 1> xwzy; \
    detail::ivector_swizzle4<4, 0, 3, 2, 2> xwzz; \
    detail::ivector_swizzle4<4, 0, 3, 2, 3> xwzw; \
    detail::ivector_swizzle4<4, 0, 3, 3, 0> xwwx; \
    detail::ivector_swizzle4<4, 0, 3, 3, 1> xwwy; \
    detail::ivector_swizzle4<4, 0, 3, 3, 2> xwwz; \
    detail::ivector_swizzle4<4, 0, 3, 3, 3> xwww; \
    detail::ivector_swizzle4<4, 1, 0, 0, 0> yxxx; \
    detail::ivector_swizzle4<4, 1, 0, 0, 1> yxxy; \
    detail::ivector_swizzle4<4, 1, 0, 0, 2> yxxz; \
    detail::ivector_swizzle4<4, 1, 0, 0, 3> yxxw; \
    detail::ivector_swizzle4<4, 1, 0, 1, 0> yxyx; \
    detail::ivector_swizzle4<4, 1, 0, 1, 1> yxyy; \
    detail::ivector_swizzle4<4, 1, 0, 1, 2> yxyz; \
    detail::ivector_swizzle4<4, 1, 0, 1, 3> yxyw; \
    detail::ivector_swizzle4<4, 1, 0, 2, 0> yxzx; \
    detail::ivector_swizzle4<4, 1, 0, 2, 1> yxzy; \
    detail::ivector_swizzle4<4, 1, 0, 2, 2> yxzz; \
    detail::ivector_swizzle4<4, 1, 0, 2, 3> yxzw; \
    detail::ivector_swizzle4<4, 1, 0, 3, 0> yxwx; \
    detail::ivector_swizzle4<4, 1, 0, 3, 1> yxwy; \
    detail::ivector_swizzle4<4, 1, 0, 3, 2> yxwz; \
    detail::ivector_swizzle4<4, 1, 0, 3, 3> yxww; \
    detail::ivector_swizzle4<4, 1, 1, 0, 0> yyxx; \
    detail::ivector_swizzle4<4, 1, 1, 0, 1> yyxy; \
    detail::ivector_swizzle4<4, 1, 1, 0, 2> yyxz; \
    detail::ivector_swizzle4<4, 1, 1, 0, 3> yyxw; \
    detail::ivector_swizzle4<4, 1, 1, 1, 0> yyyx; \
    detail::ivector_swizzle4<4, 1, 1, 1, 1> yyyy; \
    detail::ivector_swizzle4<4, 1, 1, 1, 2> yyyz; \
    detail::ivector_swizzle4<4, 1, 1, 1, 3> yyyw; \
    detail::ivector_swizzle4<4, 1, 1, 2, 0> yyzx; \
    detail::ivector_swizzle4<4, 1, 1, 2, 1> yyzy; \
    detail::ivector_swizzle4<4, 1, 1, 2, 2> yyzz; \
    detail::ivector_swizzle4<4, 1, 1, 2, 3> yyzw; \
    detail::ivector_swizzle4<4, 1, 1, 3, 0> yywx; \
    detail::ivector_swizzle4<4, 1, 1, 3, 1> yywy; \
    detail::ivector_swizzle4<4, 1, 1, 3, 2> yywz; \
    detail::ivector_swizzle4<4, 1, 1, 3, 3> yyww; \
    detail::ivector_swizzle4<4, 1, 2, 0, 0> yzxx; \
    detail::ivector_swizzle4<4, 1, 2, 0, 1> yzxy; \
    detail::ivector_swizzle4<4, 1, 2, 0, 2> yzxz; \
    detail::ivector_swizzle4<4, 1, 2, 0, 3> yzxw; \
    detail::ivector_swizzle4<4, 1, 2, 1, 0> yzyx; \
    detail::ivector_swizzle4<4, 1, 2, 1, 1> yzyy; \
    detail::ivector_swizzle4<4, 1, 2, 1, 2> yzyz; \
    detail::ivector_swizzle4<4, 1, 2, 1, 3> yzyw; \
    detail::ivector_swizzle4<4, 1, 2, 2, 0> yzzx; \
    detail::ivector_swizzle4<4, 1, 2, 2, 1> yzzy; \
    detail::ivector_swizzle4<4, 1, 2, 2, 2> yzzz; \
    detail::ivector_swizzle4<4, 1, 2, 2, 3> yzzw; \
    detail::ivector_swizzle4<4, 1, 2, 3, 0> yzwx; \
    detail::ivector_swizzle4<4, 1, 2, 3, 1> yzwy; \
    detail::ivector_swizzle4<4, 1, 2, 3, 2> yzwz; \
    detail::ivector_swizzle4<4, 1, 2, 3, 3> yzww; \
    detail::ivector_swizzle4<4, 1, 3, 0, 0> ywxx; \
    detail::ivector_swizzle4<4, 1, 3, 0, 1> ywxy; \
    detail::ivector_swizzle4<4, 1, 3, 0, 2> ywxz; \
    detail::ivector_swizzle4<4, 1, 3, 0, 3> ywxw; \
    detail::ivector_swizzle4<4, 1, 3, 1, 0> ywyx; \
    detail::ivector_swizzle4<4, 1, 3, 1, 1> ywyy; \
    detail::ivector_swizzle4<4, 1, 3, 1, 2> ywyz; \
    detail::ivector_swizzle4<4, 1, 3, 1, 3> ywyw; \
    detail::ivector_swizzle4<4, 1, 3, 2, 0> ywzx; \
    detail::ivector_swizzle4<4, 1, 3, 2, 1> ywzy; \
    detail::ivector_swizzle4<4, 1, 3, 2, 2> ywzz; \
    detail::ivector_swizzle4<4, 1, 3, 2, 3> ywzw; \
    detail::ivector_swizzle4<4, 1, 3, 3, 0> ywwx; \
    detail::ivector_swizzle4<4, 1, 3, 3, 1> ywwy; \
    detail::ivector_swizzle4<4, 1, 3, 3, 2> ywwz; \
    detail::ivector_swizzle4<4, 1, 3, 3, 3> ywww; \
    detail::ivector_swizzle4<4, 2, 0, 0, 0> zxxx; \
    detail::ivector_swizzle4<4, 2, 0, 0, 1> zxxy; \
    detail::ivector_swizzle4<4, 2, 0, 0, 2> zxxz; \
    detail::ivector_swizzle4<4, 2, 0, 0, 3> zxxw; \
    detail::ivector_swizzle4<4, 2, 0, 1, 0> zxyx; \
    detail::ivector_swizzle4<4, 2, 0, 1, 1> zxyy; \
    detail::ivector_swizzle4<4, 2, 0, 1, 2> zxyz; \
    detail::ivector_swizzle4<4, 2, 0, 1, 3> zxyw; \
    detail::ivector_swizzle4<4, 2, 0, 2, 0> zxzx; \
    detail::ivector_swizzle4<4, 2, 0, 2, 1> zxzy; \
    detail::ivector_swizzle4<4, 2, 0, 2, 2> zxzz; \
    detail::ivector_swizzle4<4, 2, 0, 2, 3> zxzw; \
    detail::ivector_swizzle4<4, 2, 0, 3, 0> zxwx; \
    detail::ivector_swizzle4<4, 2, 0, 3, 1> zxwy; \
    detail::ivector_swizzle4<4, 2, 0, 3, 2> zxwz; \
    detail::ivector_swizzle4<4, 2, 0, 3, 3> zxww; \
    detail::ivector_swizzle4<4, 2, 1, 0, 0> zyxx; \
    detail::ivector_swizzle4<4, 2, 1, 0, 1> zyxy; \
    detail::ivector_swizzle4<4, 2, 1, 0, 2> zyxz; \
    detail::ivector_swizzle4<4, 2, 1, 0, 3> zyxw; \
    detail::ivector_swizzle4<4, 2, 1, 1, 0> zyyx; \
    detail::ivector_swizzle4<4, 2, 1, 1, 1> zyyy; \
    detail::ivector_swizzle4<4, 2, 1, 1, 2> zyyz; \
    detail::ivector_swizzle4<4, 2, 1, 1, 3> zyyw; \
    detail::ivector_swizzle4<4, 2, 1, 2, 0> zyzx; \
    detail::ivector_swizzle4<4, 2, 1, 2, 1> zyzy; \
    detail::ivector_swizzle4<4, 2, 1, 2, 2> zyzz; \
    detail::ivector_swizzle4<4, 2, 1, 2, 3> zyzw; \
    detail::ivector_swizzle4<4, 2, 1, 3, 0> zywx; \
    detail::ivector_swizzle4<4, 2, 1, 3, 1> zywy; \
    detail::ivector_swizzle4<4, 2, 1, 3, 2> zywz; \
    detail::ivector_swizzle4<4, 2, 1, 3, 3> zyww; \
    detail::ivector_swizzle4<4, 2, 2, 0, 0> zzxx; \
    detail::ivector_swizzle4<4, 2, 2, 0, 1> zzxy; \
    detail::ivector_swizzle4<4, 2, 2, 0, 2> zzxz; \
    detail::ivector_swizzle4<4, 2, 2, 0, 3> zzxw; \
    detail::ivector_swizzle4<4, 2, 2, 1, 0> zzyx; \
    detail::ivector_swizzle4<4, 2, 2, 1, 1> zzyy; \
    detail::ivector_swizzle4<4, 2, 2, 1, 2> zzyz; \
    detail::ivector_swizzle4<4, 2, 2, 1, 3> zzyw; \
    detail::ivector_swizzle4<4, 2, 2, 2, 0> zzzx; \
    detail::ivector_swizzle4<4, 2, 2, 2, 1> zzzy; \
    detail::ivector_swizzle4<4, 2, 2, 2, 2> zzzz; \
    detail::ivector_swizzle4<4, 2, 2, 2, 3> zzzw; \
    detail::ivector_swizzle4<4, 2, 2, 3, 0> zzwx; \
    detail::ivector_swizzle4<4, 2, 2, 3, 1> zzwy; \
    detail::ivector_swizzle4<4, 2, 2, 3, 2> zzwz; \
    detail::ivector_swizzle4<4, 2, 2, 3, 3> zzww; \
    detail::ivector_swizzle4<4, 2, 3, 0, 0> zwxx; \
    detail::ivector_swizzle4<4, 2, 3, 0, 1> zwxy; \
    detail::ivector_swizzle4<4, 2, 3, 0, 2> zwxz; \
    detail::ivector_swizzle4<4, 2, 3, 0, 3> zwxw; \
    detail::ivector_swizzle4<4, 2, 3, 1, 0> zwyx; \
    detail::ivector_swizzle4<4, 2, 3, 1, 1> zwyy; \
    detail::ivector_swizzle4<4, 2, 3, 1, 2> zwyz; \
    detail::ivector_swizzle4<4, 2, 3, 1, 3> zwyw; \
    detail::ivector_swizzle4<4, 2, 3, 2, 0> zwzx; \
    detail::ivector_swizzle4<4, 2, 3, 2, 1> zwzy; \
    detail::ivector_swizzle4<4, 2, 3, 2, 2> zwzz; \
    detail::ivector_swizzle4<4, 2, 3, 2, 3> zwzw; \
    detail::ivector_swizzle4<4, 2, 3, 3, 0> zwwx; \
    detail::ivector_swizzle4<4, 2, 3, 3, 1> zwwy; \
    detail::ivector_swizzle4<4, 2, 3, 3, 2> zwwz; \
    detail::ivector_swizzle4<4, 2, 3, 3, 3> zwww; \
    detail::ivector_swizzle4<4, 3, 0, 0, 0> wxxx; \
    detail::ivector_swizzle4<4, 3, 0, 0, 1> wxxy; \
    detail::ivector_swizzle4<4, 3, 0, 0, 2> wxxz; \
    detail::ivector_swizzle4<4, 3, 0, 0, 3> wxxw; \
    detail::ivector_swizzle4<4, 3, 0, 1, 0> wxyx; \
    detail::ivector_swizzle4<4, 3, 0, 1, 1> wxyy; \
    detail::ivector_swizzle4<4, 3, 0, 1, 2> wxyz; \
    detail::ivector_swizzle4<4, 3, 0, 1, 3> wxyw; \
    detail::ivector_swizzle4<4, 3, 0, 2, 0> wxzx; \
    detail::ivector_swizzle4<4, 3, 0, 2, 1> wxzy; \
    detail::ivector_swizzle4<4, 3, 0, 2, 2> wxzz; \
    detail::ivector_swizzle4<4, 3, 0, 2, 3> wxzw; \
    detail::ivector_swizzle4<4, 3, 0, 3, 0> wxwx; \
    detail::ivector_swizzle4<4, 3, 0, 3, 1> wxwy; \
    detail::ivector_swizzle4<4, 3, 0, 3, 2> wxwz; \
    detail::ivector_swizzle4<4, 3, 0, 3, 3> wxww; \
    detail::ivector_swizzle4<4, 3, 1, 0, 0> wyxx; \
    detail::ivector_swizzle4<4, 3, 1, 0, 1> wyxy; \
    detail::ivector_swizzle4<4, 3, 1, 0, 2> wyxz; \
    detail::ivector_swizzle4<4, 3, 1, 0, 3> wyxw; \
    detail::ivector_swizzle4<4, 3, 1, 1, 0> wyyx; \
    detail::ivector_swizzle4<4, 3, 1, 1, 1> wyyy; \
    detail::ivector_swizzle4<4, 3, 1, 1, 2> wyyz; \
    detail::ivector_swizzle4<4, 3, 1, 1, 3> wyyw; \
    detail::ivector_swizzle4<4, 3, 1, 2, 0> wyzx; \
    detail::ivector_swizzle4<4, 3, 1, 2, 1> wyzy; \
    detail::ivector_swizzle4<4, 3, 1, 2, 2> wyzz; \
    detail::ivector_swizzle4<4, 3, 1, 2, 3> wyzw; \
    detail::ivector_swizzle4<4, 3, 1, 3, 0> wywx; \
    detail::ivector_swizzle4<4, 3, 1, 3, 1> wywy; \
    detail::ivector_swizzle4<4, 3, 1, 3, 2> wywz; \
    detail::ivector_swizzle4<4, 3, 1, 3, 3> wyww; \
    detail::ivector_swizzle4<4, 3, 2, 0, 0> wzxx; \
    detail::ivector_swizzle4<4, 3, 2, 0, 1> wzxy; \
    detail::ivector_swizzle4<4, 3, 2, 0, 2> wzxz; \
    detail::ivector_swizzle4<4, 3, 2, 0, 3> wzxw; \
    detail::ivector_swizzle4<4, 3, 2, 1, 0> wzyx; \
    detail::ivector_swizzle4<4, 3, 2, 1, 1> wzyy; \
    detail::ivector_swizzle4<4, 3, 2, 1, 2> wzyz; \
    detail::ivector_swizzle4<4, 3, 2, 1, 3> wzyw; \
    detail::ivector_swizzle4<4, 3, 2, 2, 0> wzzx; \
    detail::ivector_swizzle4<4, 3, 2, 2, 1> wzzy; \
    detail::ivector_swizzle4<4, 3, 2, 2, 2> wzzz; \
    detail::ivector_swizzle4<4, 3, 2, 2, 3> wzzw; \
    detail::ivector_swizzle4<4, 3, 2, 3, 0> wzwx; \
    detail::ivector_swizzle4<4, 3, 2, 3, 1> wzwy; \
    detail::ivector_swizzle4<4, 3, 2, 3, 2> wzwz; \
    detail::ivector_swizzle4<4, 3, 2, 3, 3> wzww; \
    detail::ivector_swizzle4<4, 3, 3, 0, 0> wwxx; \
    detail::ivector_swizzle4<4, 3, 3, 0, 1> wwxy; \
    detail::ivector_swizzle4<4, 3, 3, 0, 2> wwxz; \
    detail::ivector_swizzle4<4, 3, 3, 0, 3> wwxw; \
    detail::ivector_swizzle4<4, 3, 3, 1, 0> wwyx; \
    detail::ivector_swizzle4<4, 3, 3, 1, 1> wwyy; \
    detail::ivector_swizzle4<4, 3, 3, 1, 2> wwyz; \
    detail::ivector_swizzle4<4, 3, 3, 1, 3> wwyw; \
    detail::ivector_swizzle4<4, 3, 3, 2, 0> wwzx; \
    detail::ivector_swizzle4<4, 3, 3, 2, 1> wwzy; \
    detail::ivector_swizzle4<4, 3, 3, 2, 2> wwzz; \
    detail::ivector_swizzle4<4, 3, 3, 2, 3> wwzw; \
    detail::ivector_swizzle4<4, 3, 3, 3, 0> wwwx; \
    detail::ivector_swizzle4<4, 3, 3, 3, 1> wwwy; \
    detail::ivector_swizzle4<4, 3, 3, 3, 2> wwwz; \
    detail::ivector_swizzle4<4, 3, 3, 3, 3> wwww; \
    /* rgba family */ \
    /* rgba length 2 */ \
    detail::ivector_swizzle2<4, 0, 0> rr; \
    detail::ivector_swizzle2<4, 0, 1> rg; \
    detail::ivector_swizzle2<4, 0, 2> rb; \
    detail::ivector_swizzle2<4, 0, 3> ra; \
    detail::ivector_swizzle2<4, 1, 0> gr; \
    detail::ivector_swizzle2<4, 1, 1> gg; \
    detail::ivector_swizzle2<4, 1, 2> gb; \
    detail::ivector_swizzle2<4, 1, 3> ga; \
    detail::ivector_swizzle2<4, 2, 0> br; \
    detail::ivector_swizzle2<4, 2, 1> bg; \
    detail::ivector_swizzle2<4, 2, 2> bb; \
    detail::ivector_swizzle2<4, 2, 3> ba; \
    detail::ivector_swizzle2<4, 3, 0> ar; \
    detail::ivector_swizzle2<4, 3, 1> ag; \
    detail::ivector_swizzle2<4, 3, 2> ab; \
    detail::ivector_swizzle2<4, 3, 3> aa; \
    /* rgba length 3 */ \
    detail::ivector_swizzle3<4, 0, 0, 0> rrr; \
    detail::ivector_swizzle3<4, 0, 0, 1> rrg; \
    detail::ivector_swizzle3<4, 0, 0, 2> rrb; \
    detail::ivector_swizzle3<4, 0, 0, 3> rra; \
    detail::ivector_swizzle3<4, 0, 1, 0> rgr; \
    detail::ivector_swizzle3<4, 0, 1, 1> rgg; \
    detail::ivector_swizzle3<4, 0, 1, 2> rgb; \
    detail::ivector_swizzle3<4, 0, 1, 3> rga; \
    detail::ivector_swizzle3<4, 0, 2, 0> rbr; \
    detail::ivector_swizzle3<4, 0, 2, 1> rbg; \
    detail::ivector_swizzle3<4, 0, 2, 2> rbb; \
    detail::ivector_swizzle3<4, 0, 2, 3> rba; \
    detail::ivector_swizzle3<4, 0, 3, 0> rar; \
    detail::ivector_swizzle3<4, 0, 3, 1> rag; \
    detail::ivector_swizzle3<4, 0, 3, 2> rab; \
    detail::ivector_swizzle3<4, 0, 3, 3> raa; \
    detail::ivector_swizzle3<4, 1, 0, 0> grr; \
    detail::ivector_swizzle3<4, 1, 0, 1> grg; \
    detail::ivector_swizzle3<4, 1, 0, 2> grb; \
    detail::ivector_swizzle3<4, 1, 0, 3> gra; \
    detail::ivector_swizzle3<4, 1, 1, 0> ggr; \
    detail::ivector_swizzle3<4, 1, 1, 1> ggg; \
    detail::ivector_swizzle3<4, 1, 1, 2> ggb; \
    detail::ivector_swizzle3<4, 1, 1, 3> gga; \
    detail::ivector_swizzle3<4, 1, 2, 0> gbr; \
    detail::ivector_swizzle3<4, 1, 2, 1> gbg; \
    detail::ivector_swizzle3<4, 1, 2, 2> gbb; \
    detail::ivector_swizzle3<4, 1, 2, 3> gba; \
    detail::ivector_swizzle3<4, 1, 3, 0> gar; \
    detail::ivector_swizzle3<4, 1, 3, 1> gag; \
    detail::ivector_swizzle3<4, 1, 3, 2> gab; \
    detail::ivector_swizzle3<4, 1, 3, 3> gaa; \
    detail::ivector_swizzle3<4, 2, 0, 0> brr; \
    detail::ivector_swizzle3<4, 2, 0, 1> brg; \
    detail::ivector_swizzle3<4, 2, 0, 2> brb; \
    detail::ivector_swizzle3<4, 2, 0, 3> bra; \
    detail::ivector_swizzle3<4, 2, 1, 0> bgr; \
    detail::ivector_swizzle3<4, 2, 1, 1> bgg; \
    detail::ivector_swizzle3<4, 2, 1, 2> bgb; \
    detail::ivector_swizzle3<4, 2, 1, 3> bga; \
    detail::ivector_swizzle3<4, 2, 2, 0> bbr; \
    detail::ivector_swizzle3<4, 2, 2, 1> bbg; \
    detail::ivector_swizzle3<4, 2, 2, 2> bbb; \
    detail::ivector_swizzle3<4, 2, 2, 3> bba; \
    detail::ivector_swizzle3<4, 2, 3, 0> bar; \
    detail::ivector_swizzle3<4, 2, 3, 1> bag; \
    detail::ivector_swizzle3<4, 2, 3, 2> bab; \
    detail::ivector_swizzle3<4, 2, 3, 3> baa; \
    detail::ivector_swizzle3<4, 3, 0, 0> arr; \
    detail::ivector_swizzle3<4, 3, 0, 1> arg; \
    detail::ivector_swizzle3<4, 3, 0, 2> arb; \
    detail::ivector_swizzle3<4, 3, 0, 3> ara; \
    detail::ivector_swizzle3<4, 3, 1, 0> agr; \
    detail::ivector_swizzle3<4, 3, 1, 1> agg; \
    detail::ivector_swizzle3<4, 3, 1, 2> agb; \
    detail::ivector_swizzle3<4, 3, 1, 3> aga; \
    detail::ivector_swizzle3<4, 3, 2, 0> abr; \
    detail::ivector_swizzle3<4, 3, 2, 1> abg; \
    detail::ivector_swizzle3<4, 3, 2, 2> abb; \
    detail::ivector_swizzle3<4, 3, 2, 3> aba; \
    detail::ivector_swizzle3<4, 3, 3, 0> aar; \
    detail::ivector_swizzle3<4, 3, 3, 1> aag; \
    detail::ivector_swizzle3<4, 3, 3, 2> aab; \
    detail::ivector_swizzle3<4, 3, 3, 3> aaa; \
    /* rgba length 4 */ \
    detail::ivector_swizzle4<4, 0, 0, 0, 0> rrrr; \
    detail::ivector_swizzle4<4, 0, 0, 0, 1> rrrg; \
    detail::ivector_swizzle4<4, 0, 0, 0, 2> rrrb; \
    detail::ivector_swizzle4<4, 0, 0, 0, 3> rrra; \
    detail::ivector_swizzle4<4, 0, 0, 1, 0> rrgr; \
    detail::ivector_swizzle4<4, 0, 0, 1, 1> rrgg; \
    detail::ivector_swizzle4<4, 0, 0, 1, 2> rrgb; \
    detail::ivector_swizzle4<4, 0, 0, 1, 3> rrga; \
    detail::ivector_swizzle4<4, 0, 0, 2, 0> rrbr; \
    detail::ivector_swizzle4<4, 0, 0, 2, 1> rrbg; \
    detail::ivector_swizzle4<4, 0, 0, 2, 2> rrbb; \
    detail::ivector_swizzle4<4, 0, 0, 2, 3> rrba; \
    detail::ivector_swizzle4<4, 0, 0, 3, 0> rrar; \
    detail::ivector_swizzle4<4, 0, 0, 3, 1> rrag; \
    detail::ivector_swizzle4<4, 0, 0, 3, 2> rrab; \
    detail::ivector_swizzle4<4, 0, 0, 3, 3> rraa; \
    detail::ivector_swizzle4<4, 0, 1, 0, 0> rgrr; \
    detail::ivector_swizzle4<4, 0, 1, 0, 1> rgrg; \
    detail::ivector_swizzle4<4, 0, 1, 0, 2> rgrb; \
    detail::ivector_swizzle4<4, 0, 1, 0, 3> rgra; \
    detail::ivector_swizzle4<4, 0, 1, 1, 0> rggr; \
    detail::ivector_swizzle4<4, 0, 1, 1, 1> rggg; \
    detail::ivector_swizzle4<4, 0, 1, 1, 2> rggb; \
    detail::ivector_swizzle4<4, 0, 1, 1, 3> rgga; \
    detail::ivector_swizzle4<4, 0, 1, 2, 0> rgbr; \
    detail::ivector_swizzle4<4, 0, 1, 2, 1> rgbg; \
    detail::ivector_swizzle4<4, 0, 1, 2, 2> rgbb; \
    detail::ivector_swizzle4<4, 0, 1, 2, 3> rgba; \
    detail::ivector_swizzle4<4, 0, 1, 3, 0> rgar; \
    detail::ivector_swizzle4<4, 0, 1, 3, 1> rgag; \
    detail::ivector_swizzle4<4, 0, 1, 3, 2> rgab; \
    detail::ivector_swizzle4<4, 0, 1, 3, 3> rgaa; \
    detail::ivector_swizzle4<4, 0, 2, 0, 0> rbrr; \
    detail::ivector_swizzle4<4, 0, 2, 0, 1> rbrg; \
    detail::ivector_swizzle4<4, 0, 2, 0, 2> rbrb; \
    detail::ivector_swizzle4<4, 0, 2, 0, 3> rbra; \
    detail::ivector_swizzle4<4, 0, 2, 1, 0> rbgr; \
    detail::ivector_swizzle4<4, 0, 2, 1, 1> rbgg; \
    detail::ivector_swizzle4<4, 0, 2, 1, 2> rbgb; \
    detail::ivector_swizzle4<4, 0, 2, 1, 3> rbga; \
    detail::ivector_swizzle4<4, 0, 2, 2, 0> rbbr; \
    detail::ivector_swizzle4<4, 0, 2, 2, 1> rbbg; \
    detail::ivector_swizzle4<4, 0, 2, 2, 2> rbbb; \
    detail::ivector_swizzle4<4, 0, 2, 2, 3> rbba; \
    detail::ivector_swizzle4<4, 0, 2, 3, 0> rbar; \
    detail::ivector_swizzle4<4, 0, 2, 3, 1> rbag; \
    detail::ivector_swizzle4<4, 0, 2, 3, 2> rbab; \
    detail::ivector_swizzle4<4, 0, 2, 3, 3> rbaa; \
    detail::ivector_swizzle4<4, 0, 3, 0, 0> rarr; \
    detail::ivector_swizzle4<4, 0, 3, 0, 1> rarg; \
    detail::ivector_swizzle4<4, 0, 3, 0, 2> rarb; \
    detail::ivector_swizzle4<4, 0, 3, 0, 3> rara; \
    detail::ivector_swizzle4<4, 0, 3, 1, 0> ragr; \
    detail::ivector_swizzle4<4, 0, 3, 1, 1> ragg; \
    detail::ivector_swizzle4<4, 0, 3, 1, 2> ragb; \
    detail::ivector_swizzle4<4, 0, 3, 1, 3> raga; \
    detail::ivector_swizzle4<4, 0, 3, 2, 0> rabr; \
    detail::ivector_swizzle4<4, 0, 3, 2, 1> rabg; \
    detail::ivector_swizzle4<4, 0, 3, 2, 2> rabb; \
    detail::ivector_swizzle4<4, 0, 3, 2, 3> raba; \
    detail::ivector_swizzle4<4, 0, 3, 3, 0> raar; \
    detail::ivector_swizzle4<4, 0, 3, 3, 1> raag; \
    detail::ivector_swizzle4<4, 0, 3, 3, 2> raab; \
    detail::ivector_swizzle4<4, 0, 3, 3, 3> raaa; \
    detail::ivector_swizzle4<4, 1, 0, 0, 0> grrr; \
    detail::ivector_swizzle4<4, 1, 0, 0, 1> grrg; \
    detail::ivector_swizzle4<4, 1, 0, 0, 2> grrb; \
    detail::ivector_swizzle4<4, 1, 0, 0, 3> grra; \
    detail::ivector_swizzle4<4, 1, 0, 1, 0> grgr; \
    detail::ivector_swizzle4<4, 1, 0, 1, 1> grgg; \
    detail::ivector_swizzle4<4, 1, 0, 1, 2> grgb; \
    detail::ivector_swizzle4<4, 1, 0, 1, 3> grga; \
    detail::ivector_swizzle4<4, 1, 0, 2, 0> grbr; \
    detail::ivector_swizzle4<4, 1, 0, 2, 1> grbg; \
    detail::ivector_swizzle4<4, 1, 0, 2, 2> grbb; \
    detail::ivector_swizzle4<4, 1, 0, 2, 3> grba; \
    detail::ivector_swizzle4<4, 1, 0, 3, 0> grar; \
    detail::ivector_swizzle4<4, 1, 0, 3, 1> grag; \
    detail::ivector_swizzle4<4, 1, 0, 3, 2> grab; \
    detail::ivector_swizzle4<4, 1, 0, 3, 3> graa; \
    detail::ivector_swizzle4<4, 1, 1, 0, 0> ggrr; \
    detail::ivector_swizzle4<4, 1, 1, 0, 1> ggrg; \
    detail::ivector_swizzle4<4, 1, 1, 0, 2> ggrb; \
    detail::ivector_swizzle4<4, 1, 1, 0, 3> ggra; \
    detail::ivector_swizzle4<4, 1, 1, 1, 0> gggr; \
    detail::ivector_swizzle4<4, 1, 1, 1, 1> gggg; \
    detail::ivector_swizzle4<4, 1, 1, 1, 2> gggb; \
    detail::ivector_swizzle4<4, 1, 1, 1, 3> ggga; \
    detail::ivector_swizzle4<4, 1, 1, 2, 0> ggbr; \
    detail::ivector_swizzle4<4, 1, 1, 2, 1> ggbg; \
    detail::ivector_swizzle4<4, 1, 1, 2, 2> ggbb; \
    detail::ivector_swizzle4<4, 1, 1, 2, 3> ggba; \
    detail::ivector_swizzle4<4, 1, 1, 3, 0> ggar; \
    detail::ivector_swizzle4<4, 1, 1, 3, 1> ggag; \
    detail::ivector_swizzle4<4, 1, 1, 3, 2> ggab; \
    detail::ivector_swizzle4<4, 1, 1, 3, 3> ggaa; \
    detail::ivector_swizzle4<4, 1, 2, 0, 0> gbrr; \
    detail::ivector_swizzle4<4, 1, 2, 0, 1> gbrg; \
    detail::ivector_swizzle4<4, 1, 2, 0, 2> gbrb; \
    detail::ivector_swizzle4<4, 1, 2, 0, 3> gbra; \
    detail::ivector_swizzle4<4, 1, 2, 1, 0> gbgr; \
    detail::ivector_swizzle4<4, 1, 2, 1, 1> gbgg; \
    detail::ivector_swizzle4<4, 1, 2, 1, 2> gbgb; \
    detail::ivector_swizzle4<4, 1, 2, 1, 3> gbga; \
    detail::ivector_swizzle4<4, 1, 2, 2, 0> gbbr; \
    detail::ivector_swizzle4<4, 1, 2, 2, 1> gbbg; \
    detail::ivector_swizzle4<4, 1, 2, 2, 2> gbbb; \
    detail::ivector_swizzle4<4, 1, 2, 2, 3> gbba; \
    detail::ivector_swizzle4<4, 1, 2, 3, 0> gbar; \
    detail::ivector_swizzle4<4, 1, 2, 3, 1> gbag; \
    detail::ivector_swizzle4<4, 1, 2, 3, 2> gbab; \
    detail::ivector_swizzle4<4, 1, 2, 3, 3> gbaa; \
    detail::ivector_swizzle4<4, 1, 3, 0, 0> garr; \
    detail::ivector_swizzle4<4, 1, 3, 0, 1> garg; \
    detail::ivector_swizzle4<4, 1, 3, 0, 2> garb; \
    detail::ivector_swizzle4<4, 1, 3, 0, 3> gara; \
    detail::ivector_swizzle4<4, 1, 3, 1, 0> gagr; \
    detail::ivector_swizzle4<4, 1, 3, 1, 1> gagg; \
    detail::ivector_swizzle4<4, 1, 3, 1, 2> gagb; \
    detail::ivector_swizzle4<4, 1, 3, 1, 3> gaga; \
    detail::ivector_swizzle4<4, 1, 3, 2, 0> gabr; \
    detail::ivector_swizzle4<4, 1, 3, 2, 1> gabg; \
    detail::ivector_swizzle4<4, 1, 3, 2, 2> gabb; \
    detail::ivector_swizzle4<4, 1, 3, 2, 3> gaba; \
    detail::ivector_swizzle4<4, 1, 3, 3, 0> gaar; \
    detail::ivector_swizzle4<4, 1, 3, 3, 1> gaag; \
    detail::ivector_swizzle4<4, 1, 3, 3, 2> gaab; \
    detail::ivector_swizzle4<4, 1, 3, 3, 3> gaaa; \
    detail::ivector_swizzle4<4, 2, 0, 0, 0> brrr; \
    detail::ivector_swizzle4<4, 2, 0, 0, 1> brrg; \
    detail::ivector_swizzle4<4, 2, 0, 0, 2> brrb; \
    detail::ivector_swizzle4<4, 2, 0, 0, 3> brra; \
    detail::ivector_swizzle4<4, 2, 0, 1, 0> brgr; \
    detail::ivector_swizzle4<4, 2, 0, 1, 1> brgg; \
    detail::ivector_swizzle4<4, 2, 0, 1, 2> brgb; \
    detail::ivector_swizzle4<4, 2, 0, 1, 3> brga; \
    detail::ivector_swizzle4<4, 2, 0, 2, 0> brbr; \
    detail::ivector_swizzle4<4, 2, 0, 2, 1> brbg; \
    detail::ivector_swizzle4<4, 2, 0, 2, 2> brbb; \
    detail::ivector_swizzle4<4, 2, 0, 2, 3> brba; \
    detail::ivector_swizzle4<4, 2, 0, 3, 0> brar; \
    detail::ivector_swizzle4<4, 2, 0, 3, 1> brag; \
    detail::ivector_swizzle4<4, 2, 0, 3, 2> brab; \
    detail::ivector_swizzle4<4, 2, 0, 3, 3> braa; \
    detail::ivector_swizzle4<4, 2, 1, 0, 0> bgrr; \
    detail::ivector_swizzle4<4, 2, 1, 0, 1> bgrg; \
    detail::ivector_swizzle4<4, 2, 1, 0, 2> bgrb; \
    detail::ivector_swizzle4<4, 2, 1, 0, 3> bgra; \
    detail::ivector_swizzle4<4, 2, 1, 1, 0> bggr; \
    detail::ivector_swizzle4<4, 2, 1, 1, 1> bggg; \
    detail::ivector_swizzle4<4, 2, 1, 1, 2> bggb; \
    detail::ivector_swizzle4<4, 2, 1, 1, 3> bgga; \
    detail::ivector_swizzle4<4, 2, 1, 2, 0> bgbr; \
    detail::ivector_swizzle4<4, 2, 1, 2, 1> bgbg; \
    detail::ivector_swizzle4<4, 2, 1, 2, 2> bgbb; \
    detail::ivector_swizzle4<4, 2, 1, 2, 3> bgba; \
    detail::ivector_swizzle4<4, 2, 1, 3, 0> bgar; \
    detail::ivector_swizzle4<4, 2, 1, 3, 1> bgag; \
    detail::ivector_swizzle4<4, 2, 1, 3, 2> bgab; \
    detail::ivector_swizzle4<4, 2, 1, 3, 3> bgaa; \
    detail::ivector_swizzle4<4, 2, 2, 0, 0> bbrr; \
    detail::ivector_swizzle4<4, 2, 2, 0, 1> bbrg; \
    detail::ivector_swizzle4<4, 2, 2, 0, 2> bbrb; \
    detail::ivector_swizzle4<4, 2, 2, 0, 3> bbra; \
    detail::ivector_swizzle4<4, 2, 2, 1, 0> bbgr; \
    detail::ivector_swizzle4<4, 2, 2, 1, 1> bbgg; \
    detail::ivector_swizzle4<4, 2, 2, 1, 2> bbgb; \
    detail::ivector_swizzle4<4, 2, 2, 1, 3> bbga; \
    detail::ivector_swizzle4<4, 2, 2, 2, 0> bbbr; \
    detail::ivector_swizzle4<4, 2, 2, 2, 1> bbbg; \
    detail::ivector_swizzle4<4, 2, 2, 2, 2> bbbb; \
    detail::ivector_swizzle4<4, 2, 2, 2, 3> bbba; \
    detail::ivector_swizzle4<4, 2, 2, 3, 0> bbar; \
    detail::ivector_swizzle4<4, 2, 2, 3, 1> bbag; \
    detail::ivector_swizzle4<4, 2, 2, 3, 2> bbab; \
    detail::ivector_swizzle4<4, 2, 2, 3, 3> bbaa; \
    detail::ivector_swizzle4<4, 2, 3, 0, 0> barr; \
    detail::ivector_swizzle4<4, 2, 3, 0, 1> barg; \
    detail::ivector_swizzle4<4, 2, 3, 0, 2> barb; \
    detail::ivector_swizzle4<4, 2, 3, 0, 3> bara; \
    detail::ivector_swizzle4<4, 2, 3, 1, 0> bagr; \
    detail::ivector_swizzle4<4, 2, 3, 1, 1> bagg; \
    detail::ivector_swizzle4<4, 2, 3, 1, 2> bagb; \
    detail::ivector_swizzle4<4, 2, 3, 1, 3> baga; \
    detail::ivector_swizzle4<4, 2, 3, 2, 0> babr; \
    detail::ivector_swizzle4<4, 2, 3, 2, 1> babg; \
    detail::ivector_swizzle4<4, 2, 3, 2, 2> babb; \
    detail::ivector_swizzle4<4, 2, 3, 2, 3> baba; \
    detail::ivector_swizzle4<4, 2, 3, 3, 0> baar; \
    detail::ivector_swizzle4<4, 2, 3, 3, 1> baag; \
    detail::ivector_swizzle4<4, 2, 3, 3, 2> baab; \
    detail::ivector_swizzle4<4, 2, 3, 3, 3> baaa; \
    detail::ivector_swizzle4<4, 3, 0, 0, 0> arrr; \
    detail::ivector_swizzle4<4, 3, 0, 0, 1> arrg; \
    detail::ivector_swizzle4<4, 3, 0, 0, 2> arrb; \
    detail::ivector_swizzle4<4, 3, 0, 0, 3> arra; \
    detail::ivector_swizzle4<4, 3, 0, 1, 0> argr; \
    detail::ivector_swizzle4<4, 3, 0, 1, 1> argg; \
    detail::ivector_swizzle4<4, 3, 0, 1, 2> argb; \
    detail::ivector_swizzle4<4, 3, 0, 1, 3> arga; \
    detail::ivector_swizzle4<4, 3, 0, 2, 0> arbr; \
    detail::ivector_swizzle4<4, 3, 0, 2, 1> arbg; \
    detail::ivector_swizzle4<4, 3, 0, 2, 2> arbb; \
    detail::ivector_swizzle4<4, 3, 0, 2, 3> arba; \
    detail::ivector_swizzle4<4, 3, 0, 3, 0> arar; \
    detail::ivector_swizzle4<4, 3, 0, 3, 1> arag; \
    detail::ivector_swizzle4<4, 3, 0, 3, 2> arab; \
    detail::ivector_swizzle4<4, 3, 0, 3, 3> araa; \
    detail::ivector_swizzle4<4, 3, 1, 0, 0> agrr; \
    detail::ivector_swizzle4<4, 3, 1, 0, 1> agrg; \
    detail::ivector_swizzle4<4, 3, 1, 0, 2> agrb; \
    detail::ivector_swizzle4<4, 3, 1, 0, 3> agra; \
    detail::ivector_swizzle4<4, 3, 1, 1, 0> aggr; \
    detail::ivector_swizzle4<4, 3, 1, 1, 1> aggg; \
    detail::ivector_swizzle4<4, 3, 1, 1, 2> aggb; \
    detail::ivector_swizzle4<4, 3, 1, 1, 3> agga; \
    detail::ivector_swizzle4<4, 3, 1, 2, 0> agbr; \
    detail::ivector_swizzle4<4, 3, 1, 2, 1> agbg; \
    detail::ivector_swizzle4<4, 3, 1, 2, 2> agbb; \
    detail::ivector_swizzle4<4, 3, 1, 2, 3> agba; \
    detail::ivector_swizzle4<4, 3, 1, 3, 0> agar; \
    detail::ivector_swizzle4<4, 3, 1, 3, 1> agag; \
    detail::ivector_swizzle4<4, 3, 1, 3, 2> agab; \
    detail::ivector_swizzle4<4, 3, 1, 3, 3> agaa; \
    detail::ivector_swizzle4<4, 3, 2, 0, 0> abrr; \
    detail::ivector_swizzle4<4, 3, 2, 0, 1> abrg; \
    detail::ivector_swizzle4<4, 3, 2, 0, 2> abrb; \
    detail::ivector_swizzle4<4, 3, 2, 0, 3> abra; \
    detail::ivector_swizzle4<4, 3, 2, 1, 0> abgr; \
    detail::ivector_swizzle4<4, 3, 2, 1, 1> abgg; \
    detail::ivector_swizzle4<4, 3, 2, 1, 2> abgb; \
    detail::ivector_swizzle4<4, 3, 2, 1, 3> abga; \
    detail::ivector_swizzle4<4, 3, 2, 2, 0> abbr; \
    detail::ivector_swizzle4<4, 3, 2, 2, 1> abbg; \
    detail::ivector_swizzle4<4, 3, 2, 2, 2> abbb; \
    detail::ivector_swizzle4<4, 3, 2, 2, 3> abba; \
    detail::ivector_swizzle4<4, 3, 2, 3, 0> abar; \
    detail::ivector_swizzle4<4, 3, 2, 3, 1> abag; \
    detail::ivector_swizzle4<4, 3, 2, 3, 2> abab; \
    detail::ivector_swizzle4<4, 3, 2, 3, 3> abaa; \
    detail::ivector_swizzle4<4, 3, 3, 0, 0> aarr; \
    detail::ivector_swizzle4<4, 3, 3, 0, 1> aarg; \
    detail::ivector_swizzle4<4, 3, 3, 0, 2> aarb; \
    detail::ivector_swizzle4<4, 3, 3, 0, 3> aara; \
    detail::ivector_swizzle4<4, 3, 3, 1, 0> aagr; \
    detail::ivector_swizzle4<4, 3, 3, 1, 1> aagg; \
    detail::ivector_swizzle4<4, 3, 3, 1, 2> aagb; \
    detail::ivector_swizzle4<4, 3, 3, 1, 3> aaga; \
    detail::ivector_swizzle4<4, 3, 3, 2, 0> aabr; \
    detail::ivector_swizzle4<4, 3, 3, 2, 1> aabg; \
    detail::ivector_swizzle4<4, 3, 3, 2, 2> aabb; \
    detail::ivector_swizzle4<4, 3, 3, 2, 3> aaba; \
    detail::ivector_swizzle4<4, 3, 3, 3, 0> aaar; \
    detail::ivector_swizzle4<4, 3, 3, 3, 1> aaag; \
    detail::ivector_swizzle4<4, 3, 3, 3, 2> aaab; \
    detail::ivector_swizzle4<4, 3, 3, 3, 3> aaaa; \
    /* stpq family */ \
    /* stpq length 2 */ \
    detail::ivector_swizzle2<4, 0, 0> ss; \
    detail::ivector_swizzle2<4, 0, 1> st; \
    detail::ivector_swizzle2<4, 0, 2> sp; \
    detail::ivector_swizzle2<4, 0, 3> sq; \
    detail::ivector_swizzle2<4, 1, 0> ts; \
    detail::ivector_swizzle2<4, 1, 1> tt; \
    detail::ivector_swizzle2<4, 1, 2> tp; \
    detail::ivector_swizzle2<4, 1, 3> tq; \
    detail::ivector_swizzle2<4, 2, 0> ps; \
    detail::ivector_swizzle2<4, 2, 1> pt; \
    detail::ivector_swizzle2<4, 2, 2> pp; \
    detail::ivector_swizzle2<4, 2, 3> pq; \
    detail::ivector_swizzle2<4, 3, 0> qs; \
    detail::ivector_swizzle2<4, 3, 1> qt; \
    detail::ivector_swizzle2<4, 3, 2> qp; \
    detail::ivector_swizzle2<4, 3, 3> qq; \
    /* stpq length 3 */ \
    detail::ivector_swizzle3<4, 0, 0, 0> sss; \
    detail::ivector_swizzle3<4, 0, 0, 1> sst; \
    detail::ivector_swizzle3<4, 0, 0, 2> ssp; \
    detail::ivector_swizzle3<4, 0, 0, 3> ssq; \
    detail::ivector_swizzle3<4, 0, 1, 0> sts; \
    detail::ivector_swizzle3<4, 0, 1, 1> stt; \
    detail::ivector_swizzle3<4, 0, 1, 2> stp; \
    detail::ivector_swizzle3<4, 0, 1, 3> stq; \
    detail::ivector_swizzle3<4, 0, 2, 0> sps; \
    detail::ivector_swizzle3<4, 0, 2, 1> spt; \
    detail::ivector_swizzle3<4, 0, 2, 2> spp; \
    detail::ivector_swizzle3<4, 0, 2, 3> spq; \
    detail::ivector_swizzle3<4, 0, 3, 0> sqs; \
    detail::ivector_swizzle3<4, 0, 3, 1> sqt; \
    detail::ivector_swizzle3<4, 0, 3, 2> sqp; \
    detail::ivector_swizzle3<4, 0, 3, 3> sqq; \
    detail::ivector_swizzle3<4, 1, 0, 0> tss; \
    detail::ivector_swizzle3<4, 1, 0, 1> tst; \
    detail::ivector_swizzle3<4, 1, 0, 2> tsp; \
    detail::ivector_swizzle3<4, 1, 0, 3> tsq; \
    detail::ivector_swizzle3<4, 1, 1, 0> tts; \
    detail::ivector_swizzle3<4, 1, 1, 1> ttt; \
    detail::ivector_swizzle3<4, 1, 1, 2> ttp; \
    detail::ivector_swizzle3<4, 1, 1, 3> ttq; \
    detail::ivector_swizzle3<4, 1, 2, 0> tps; \
    detail::ivector_swizzle3<4, 1, 2, 1> tpt; \
    detail::ivector_swizzle3<4, 1, 2, 2> tpp; \
    detail::ivector_swizzle3<4, 1, 2, 3> tpq; \
    detail::ivector_swizzle3<4, 1, 3, 0> tqs; \
    detail::ivector_swizzle3<4, 1, 3, 1> tqt; \
    detail::ivector_swizzle3<4, 1, 3, 2> tqp; \
    detail::ivector_swizzle3<4, 1, 3, 3> tqq; \
    detail::ivector_swizzle3<4, 2, 0, 0> pss; \
    detail::ivector_swizzle3<4, 2, 0, 1> pst; \
    detail::ivector_swizzle3<4, 2, 0, 2> psp; \
    detail::ivector_swizzle3<4, 2, 0, 3> psq; \
    detail::ivector_swizzle3<4, 2, 1, 0> pts; \
    detail::ivector_swizzle3<4, 2, 1, 1> ptt; \
    detail::ivector_swizzle3<4, 2, 1, 2> ptp; \
    detail::ivector_swizzle3<4, 2, 1, 3> ptq; \
    detail::ivector_swizzle3<4, 2, 2, 0> pps; \
    detail::ivector_swizzle3<4, 2, 2, 1> ppt; \
    detail::ivector_swizzle3<4, 2, 2, 2> ppp; \
    detail::ivector_swizzle3<4, 2, 2, 3> ppq; \
    detail::ivector_swizzle3<4, 2, 3, 0> pqs; \
    detail::ivector_swizzle3<4, 2, 3, 1> pqt; \
    detail::ivector_swizzle3<4, 2, 3, 2> pqp; \
    detail::ivector_swizzle3<4, 2, 3, 3> pqq; \
    detail::ivector_swizzle3<4, 3, 0, 0> qss; \
    detail::ivector_swizzle3<4, 3, 0, 1> qst; \
    detail::ivector_swizzle3<4, 3, 0, 2> qsp; \
    detail::ivector_swizzle3<4, 3, 0, 3> qsq; \
    detail::ivector_swizzle3<4, 3, 1, 0> qts; \
    detail::ivector_swizzle3<4, 3, 1, 1> qtt; \
    detail::ivector_swizzle3<4, 3, 1, 2> qtp; \
    detail::ivector_swizzle3<4, 3, 1, 3> qtq; \
    detail::ivector_swizzle3<4, 3, 2, 0> qps; \
    detail::ivector_swizzle3<4, 3, 2, 1> qpt; \
    detail::ivector_swizzle3<4, 3, 2, 2> qpp; \
    detail::ivector_swizzle3<4, 3, 2, 3> qpq; \
    detail::ivector_swizzle3<4, 3, 3, 0> qqs; \
    detail::ivector_swizzle3<4, 3, 3, 1> qqt; \
    detail::ivector_swizzle3<4, 3, 3, 2> qqp; \
    detail::ivector_swizzle3<4, 3, 3, 3> qqq; \
    /* stpq length 4 */ \
    detail::ivector_swizzle4<4, 0, 0, 0, 0> ssss; \
    detail::ivector_swizzle4<4, 0, 0, 0, 1> ssst; \
    detail::ivector_swizzle4<4, 0, 0, 0, 2> sssp; \
    detail::ivector_swizzle4<4, 0, 0, 0, 3> sssq; \
    detail::ivector_swizzle4<4, 0, 0, 1, 0> ssts; \
    detail::ivector_swizzle4<4, 0, 0, 1, 1> sstt; \
    detail::ivector_swizzle4<4, 0, 0, 1, 2> sstp; \
    detail::ivector_swizzle4<4, 0, 0, 1, 3> sstq; \
    detail::ivector_swizzle4<4, 0, 0, 2, 0> ssps; \
    detail::ivector_swizzle4<4, 0, 0, 2, 1> sspt; \
    detail::ivector_swizzle4<4, 0, 0, 2, 2> sspp; \
    detail::ivector_swizzle4<4, 0, 0, 2, 3> sspq; \
    detail::ivector_swizzle4<4, 0, 0, 3, 0> ssqs; \
    detail::ivector_swizzle4<4, 0, 0, 3, 1> ssqt; \
    detail::ivector_swizzle4<4, 0, 0, 3, 2> ssqp; \
    detail::ivector_swizzle4<4, 0, 0, 3, 3> ssqq; \
    detail::ivector_swizzle4<4, 0, 1, 0, 0> stss; \
    detail::ivector_swizzle4<4, 0, 1, 0, 1> stst; \
    detail::ivector_swizzle4<4, 0, 1, 0, 2> stsp; \
    detail::ivector_swizzle4<4, 0, 1, 0, 3> stsq; \
    detail::ivector_swizzle4<4, 0, 1, 1, 0> stts; \
    detail::ivector_swizzle4<4, 0, 1, 1, 1> sttt; \
    detail::ivector_swizzle4<4, 0, 1, 1, 2> sttp; \
    detail::ivector_swizzle4<4, 0, 1, 1, 3> sttq; \
    detail::ivector_swizzle4<4, 0, 1, 2, 0> stps; \
    detail::ivector_swizzle4<4, 0, 1, 2, 1> stpt; \
    detail::ivector_swizzle4<4, 0, 1, 2, 2> stpp; \
    detail::ivector_swizzle4<4, 0, 1, 2, 3> stpq; \
    detail::ivector_swizzle4<4, 0, 1, 3, 0> stqs; \
    detail::ivector_swizzle4<4, 0, 1, 3, 1> stqt; \
    detail::ivector_swizzle4<4, 0, 1, 3, 2> stqp; \
    detail::ivector_swizzle4<4, 0, 1, 3, 3> stqq; \
    detail::ivector_swizzle4<4, 0, 2, 0, 0> spss; \
    detail::ivector_swizzle4<4, 0, 2, 0, 1> spst; \
    detail::ivector_swizzle4<4, 0, 2, 0, 2> spsp; \
    detail::ivector_swizzle4<4, 0, 2, 0, 3> spsq; \
    detail::ivector_swizzle4<4, 0, 2, 1, 0> spts; \
    detail::ivector_swizzle4<4, 0, 2, 1, 1> sptt; \
    detail::ivector_swizzle4<4, 0, 2, 1, 2> sptp; \
    detail::ivector_swizzle4<4, 0, 2, 1, 3> sptq; \
    detail::ivector_swizzle4<4, 0, 2, 2, 0> spps; \
    detail::ivector_swizzle4<4, 0, 2, 2, 1> sppt; \
    detail::ivector_swizzle4<4, 0, 2, 2, 2> sppp; \
    detail::ivector_swizzle4<4, 0, 2, 2, 3> sppq; \
    detail::ivector_swizzle4<4, 0, 2, 3, 0> spqs; \
    detail::ivector_swizzle4<4, 0, 2, 3, 1> spqt; \
    detail::ivector_swizzle4<4, 0, 2, 3, 2> spqp; \
    detail::ivector_swizzle4<4, 0, 2, 3, 3> spqq; \
    detail::ivector_swizzle4<4, 0, 3, 0, 0> sqss; \
    detail::ivector_swizzle4<4, 0, 3, 0, 1> sqst; \
    detail::ivector_swizzle4<4, 0, 3, 0, 2> sqsp; \
    detail::ivector_swizzle4<4, 0, 3, 0, 3> sqsq; \
    detail::ivector_swizzle4<4, 0, 3, 1, 0> sqts; \
    detail::ivector_swizzle4<4, 0, 3, 1, 1> sqtt; \
    detail::ivector_swizzle4<4, 0, 3, 1, 2> sqtp; \
    detail::ivector_swizzle4<4, 0, 3, 1, 3> sqtq; \
    detail::ivector_swizzle4<4, 0, 3, 2, 0> sqps; \
    detail::ivector_swizzle4<4, 0, 3, 2, 1> sqpt; \
    detail::ivector_swizzle4<4, 0, 3, 2, 2> sqpp; \
    detail::ivector_swizzle4<4, 0, 3, 2, 3> sqpq; \
    detail::ivector_swizzle4<4, 0, 3, 3, 0> sqqs; \
    detail::ivector_swizzle4<4, 0, 3, 3, 1> sqqt; \
    detail::ivector_swizzle4<4, 0, 3, 3, 2> sqqp; \
    detail::ivector_swizzle4<4, 0, 3, 3, 3> sqqq; \
    detail::ivector_swizzle4<4, 1, 0, 0, 0> tsss; \
    detail::ivector_swizzle4<4, 1, 0, 0, 1> tsst; \
    detail::ivector_swizzle4<4, 1, 0, 0, 2> tssp; \
    detail::ivector_swizzle4<4, 1, 0, 0, 3> tssq; \
    detail::ivector_swizzle4<4, 1, 0, 1, 0> tsts; \
    detail::ivector_swizzle4<4, 1, 0, 1, 1> tstt; \
    detail::ivector_swizzle4<4, 1, 0, 1, 2> tstp; \
    detail::ivector_swizzle4<4, 1, 0, 1, 3> tstq; \
    detail::ivector_swizzle4<4, 1, 0, 2, 0> tsps; \
    detail::ivector_swizzle4<4, 1, 0, 2, 1> tspt; \
    detail::ivector_swizzle4<4, 1, 0, 2, 2> tspp; \
    detail::ivector_swizzle4<4, 1, 0, 2, 3> tspq; \
    detail::ivector_swizzle4<4, 1, 0, 3, 0> tsqs; \
    detail::ivector_swizzle4<4, 1, 0, 3, 1> tsqt; \
    detail::ivector_swizzle4<4, 1, 0, 3, 2> tsqp; \
    detail::ivector_swizzle4<4, 1, 0, 3, 3> tsqq; \
    detail::ivector_swizzle4<4, 1, 1, 0, 0> ttss; \
    detail::ivector_swizzle4<4, 1, 1, 0, 1> ttst; \
    detail::ivector_swizzle4<4, 1, 1, 0, 2> ttsp; \
    detail::ivector_swizzle4<4, 1, 1, 0, 3> ttsq; \
    detail::ivector_swizzle4<4, 1, 1, 1, 0> ttts; \
    detail::ivector_swizzle4<4, 1, 1, 1, 1> tttt; \
    detail::ivector_swizzle4<4, 1, 1, 1, 2> tttp; \
    detail::ivector_swizzle4<4, 1, 1, 1, 3> tttq; \
    detail::ivector_swizzle4<4, 1, 1, 2, 0> ttps; \
    detail::ivector_swizzle4<4, 1, 1, 2, 1> ttpt; \
    detail::ivector_swizzle4<4, 1, 1, 2, 2> ttpp; \
    detail::ivector_swizzle4<4, 1, 1, 2, 3> ttpq; \
    detail::ivector_swizzle4<4, 1, 1, 3, 0> ttqs; \
    detail::ivector_swizzle4<4, 1, 1, 3, 1> ttqt; \
    detail::ivector_swizzle4<4, 1, 1, 3, 2> ttqp; \
    detail::ivector_swizzle4<4, 1, 1, 3, 3> ttqq; \
    detail::ivector_swizzle4<4, 1, 2, 0, 0> tpss; \
    detail::ivector_swizzle4<4, 1, 2, 0, 1> tpst; \
    detail::ivector_swizzle4<4, 1, 2, 0, 2> tpsp; \
    detail::ivector_swizzle4<4, 1, 2, 0, 3> tpsq; \
    detail::ivector_swizzle4<4, 1, 2, 1, 0> tpts; \
    detail::ivector_swizzle4<4, 1, 2, 1, 1> tptt; \
    detail::ivector_swizzle4<4, 1, 2, 1, 2> tptp; \
    detail::ivector_swizzle4<4, 1, 2, 1, 3> tptq; \
    detail::ivector_swizzle4<4, 1, 2, 2, 0> tpps; \
    detail::ivector_swizzle4<4, 1, 2, 2, 1> tppt; \
    detail::ivector_swizzle4<4, 1, 2, 2, 2> tppp; \
    detail::ivector_swizzle4<4, 1, 2, 2, 3> tppq; \
    detail::ivector_swizzle4<4, 1, 2, 3, 0> tpqs; \
    detail::ivector_swizzle4<4, 1, 2, 3, 1> tpqt; \
    detail::ivector_swizzle4<4, 1, 2, 3, 2> tpqp; \
    detail::ivector_swizzle4<4, 1, 2, 3, 3> tpqq; \
    detail::ivector_swizzle4<4, 1, 3, 0, 0> tqss; \
    detail::ivector_swizzle4<4, 1, 3, 0, 1> tqst; \
    detail::ivector_swizzle4<4, 1, 3, 0, 2> tqsp; \
    detail::ivector_swizzle4<4, 1, 3, 0, 3> tqsq; \
    detail::ivector_swizzle4<4, 1, 3, 1, 0> tqts; \
    detail::ivector_swizzle4<4, 1, 3, 1, 1> tqtt; \
    detail::ivector_swizzle4<4, 1, 3, 1, 2> tqtp; \
    detail::ivector_swizzle4<4, 1, 3, 1, 3> tqtq; \
    detail::ivector_swizzle4<4, 1, 3, 2, 0> tqps; \
    detail::ivector_swizzle4<4, 1, 3, 2, 1> tqpt; \
    detail::ivector_swizzle4<4, 1, 3, 2, 2> tqpp; \
    detail::ivector_swizzle4<4, 1, 3, 2, 3> tqpq; \
    detail::ivector_swizzle4<4, 1, 3, 3, 0> tqqs; \
    detail::ivector_swizzle4<4, 1, 3, 3, 1> tqqt; \
    detail::ivector_swizzle4<4, 1, 3, 3, 2> tqqp; \
    detail::ivector_swizzle4<4, 1, 3, 3, 3> tqqq; \
    detail::ivector_swizzle4<4, 2, 0, 0, 0> psss; \
    detail::ivector_swizzle4<4, 2, 0, 0, 1> psst; \
    detail::ivector_swizzle4<4, 2, 0, 0, 2> pssp; \
    detail::ivector_swizzle4<4, 2, 0, 0, 3> pssq; \
    detail::ivector_swizzle4<4, 2, 0, 1, 0> psts; \
    detail::ivector_swizzle4<4, 2, 0, 1, 1> pstt; \
    detail::ivector_swizzle4<4, 2, 0, 1, 2> pstp; \
    detail::ivector_swizzle4<4, 2, 0, 1, 3> pstq; \
    detail::ivector_swizzle4<4, 2, 0, 2, 0> psps; \
    detail::ivector_swizzle4<4, 2, 0, 2, 1> pspt; \
    detail::ivector_swizzle4<4, 2, 0, 2, 2> pspp; \
    detail::ivector_swizzle4<4, 2, 0, 2, 3> pspq; \
    detail::ivector_swizzle4<4, 2, 0, 3, 0> psqs; \
    detail::ivector_swizzle4<4, 2, 0, 3, 1> psqt; \
    detail::ivector_swizzle4<4, 2, 0, 3, 2> psqp; \
    detail::ivector_swizzle4<4, 2, 0, 3, 3> psqq; \
    detail::ivector_swizzle4<4, 2, 1, 0, 0> ptss; \
    detail::ivector_swizzle4<4, 2, 1, 0, 1> ptst; \
    detail::ivector_swizzle4<4, 2, 1, 0, 2> ptsp; \
    detail::ivector_swizzle4<4, 2, 1, 0, 3> ptsq; \
    detail::ivector_swizzle4<4, 2, 1, 1, 0> ptts; \
    detail::ivector_swizzle4<4, 2, 1, 1, 1> pttt; \
    detail::ivector_swizzle4<4, 2, 1, 1, 2> pttp; \
    detail::ivector_swizzle4<4, 2, 1, 1, 3> pttq; \
    detail::ivector_swizzle4<4, 2, 1, 2, 0> ptps; \
    detail::ivector_swizzle4<4, 2, 1, 2, 1> ptpt; \
    detail::ivector_swizzle4<4, 2, 1, 2, 2> ptpp; \
    detail::ivector_swizzle4<4, 2, 1, 2, 3> ptpq; \
    detail::ivector_swizzle4<4, 2, 1, 3, 0> ptqs; \
    detail::ivector_swizzle4<4, 2, 1, 3, 1> ptqt; \
    detail::ivector_swizzle4<4, 2, 1, 3, 2> ptqp; \
    detail::ivector_swizzle4<4, 2, 1, 3, 3> ptqq; \
    detail::ivector_swizzle4<4, 2, 2, 0, 0> ppss; \
    detail::ivector_swizzle4<4, 2, 2, 0, 1> ppst; \
    detail::ivector_swizzle4<4, 2, 2, 0, 2> ppsp; \
    detail::ivector_swizzle4<4, 2, 2, 0, 3> ppsq; \
    detail::ivector_swizzle4<4, 2, 2, 1, 0> ppts; \
    detail::ivector_swizzle4<4, 2, 2, 1, 1> pptt; \
    detail::ivector_swizzle4<4, 2, 2, 1, 2> pptp; \
    detail::ivector_swizzle4<4, 2, 2, 1, 3> pptq; \
    detail::ivector_swizzle4<4, 2, 2, 2, 0> ppps; \
    detail::ivector_swizzle4<4, 2, 2, 2, 1> pppt; \
    detail::ivector_swizzle4<4, 2, 2, 2, 2> pppp; \
    detail::ivector_swizzle4<4, 2, 2, 2, 3> pppq; \
    detail::ivector_swizzle4<4, 2, 2, 3, 0> ppqs; \
    detail::ivector_swizzle4<4, 2, 2, 3, 1> ppqt; \
    detail::ivector_swizzle4<4, 2, 2, 3, 2> ppqp; \
    detail::ivector_swizzle4<4, 2, 2, 3, 3> ppqq; \
    detail::ivector_swizzle4<4, 2, 3, 0, 0> pqss; \
    detail::ivector_swizzle4<4, 2, 3, 0, 1> pqst; \
    detail::ivector_swizzle4<4, 2, 3, 0, 2> pqsp; \
    detail::ivector_swizzle4<4, 2, 3, 0, 3> pqsq; \
    detail::ivector_swizzle4<4, 2, 3, 1, 0> pqts; \
    detail::ivector_swizzle4<4, 2, 3, 1, 1> pqtt; \
    detail::ivector_swizzle4<4, 2, 3, 1, 2> pqtp; \
    detail::ivector_swizzle4<4, 2, 3, 1, 3> pqtq; \
    detail::ivector_swizzle4<4, 2, 3, 2, 0> pqps; \
    detail::ivector_swizzle4<4, 2, 3, 2, 1> pqpt; \
    detail::ivector_swizzle4<4, 2, 3, 2, 2> pqpp; \
    detail::ivector_swizzle4<4, 2, 3, 2, 3> pqpq; \
    detail::ivector_swizzle4<4, 2, 3, 3, 0> pqqs; \
    detail::ivector_swizzle4<4, 2, 3, 3, 1> pqqt; \
    detail::ivector_swizzle4<4, 2, 3, 3, 2> pqqp; \
    detail::ivector_swizzle4<4, 2, 3, 3, 3> pqqq; \
    detail::ivector_swizzle4<4, 3, 0, 0, 0> qsss; \
    detail::ivector_swizzle4<4, 3, 0, 0, 1> qsst; \
    detail::ivector_swizzle4<4, 3, 0, 0, 2> qssp; \
    detail::ivector_swizzle4<4, 3, 0, 0, 3> qssq; \
    detail::ivector_swizzle4<4, 3, 0, 1, 0> qsts; \
    detail::ivector_swizzle4<4, 3, 0, 1, 1> qstt; \
    detail::ivector_swizzle4<4, 3, 0, 1, 2> qstp; \
    detail::ivector_swizzle4<4, 3, 0, 1, 3> qstq; \
    detail::ivector_swizzle4<4, 3, 0, 2, 0> qsps; \
    detail::ivector_swizzle4<4, 3, 0, 2, 1> qspt; \
    detail::ivector_swizzle4<4, 3, 0, 2, 2> qspp; \
    detail::ivector_swizzle4<4, 3, 0, 2, 3> qspq; \
    detail::ivector_swizzle4<4, 3, 0, 3, 0> qsqs; \
    detail::ivector_swizzle4<4, 3, 0, 3, 1> qsqt; \
    detail::ivector_swizzle4<4, 3, 0, 3, 2> qsqp; \
    detail::ivector_swizzle4<4, 3, 0, 3, 3> qsqq; \
    detail::ivector_swizzle4<4, 3, 1, 0, 0> qtss; \
    detail::ivector_swizzle4<4, 3, 1, 0, 1> qtst; \
    detail::ivector_swizzle4<4, 3, 1, 0, 2> qtsp; \
    detail::ivector_swizzle4<4, 3, 1, 0, 3> qtsq; \
    detail::ivector_swizzle4<4, 3, 1, 1, 0> qtts; \
    detail::ivector_swizzle4<4, 3, 1, 1, 1> qttt; \
    detail::ivector_swizzle4<4, 3, 1, 1, 2> qttp; \
    detail::ivector_swizzle4<4, 3, 1, 1, 3> qttq; \
    detail::ivector_swizzle4<4, 3, 1, 2, 0> qtps; \
    detail::ivector_swizzle4<4, 3, 1, 2, 1> qtpt; \
    detail::ivector_swizzle4<4, 3, 1, 2, 2> qtpp; \
    detail::ivector_swizzle4<4, 3, 1, 2, 3> qtpq; \
    detail::ivector_swizzle4<4, 3, 1, 3, 0> qtqs; \
    detail::ivector_swizzle4<4, 3, 1, 3, 1> qtqt; \
    detail::ivector_swizzle4<4, 3, 1, 3, 2> qtqp; \
    detail::ivector_swizzle4<4, 3, 1, 3, 3> qtqq; \
    detail::ivector_swizzle4<4, 3, 2, 0, 0> qpss; \
    detail::ivector_swizzle4<4, 3, 2, 0, 1> qpst; \
    detail::ivector_swizzle4<4, 3, 2, 0, 2> qpsp; \
    detail::ivector_swizzle4<4, 3, 2, 0, 3> qpsq; \
    detail::ivector_swizzle4<4, 3, 2, 1, 0> qpts; \
    detail::ivector_swizzle4<4, 3, 2, 1, 1> qptt; \
    detail::ivector_swizzle4<4, 3, 2, 1, 2> qptp; \
    detail::ivector_swizzle4<4, 3, 2, 1, 3> qptq; \
    detail::ivector_swizzle4<4, 3, 2, 2, 0> qpps; \
    detail::ivector_swizzle4<4, 3, 2, 2, 1> qppt; \
    detail::ivector_swizzle4<4, 3, 2, 2, 2> qppp; \
    detail::ivector_swizzle4<4, 3, 2, 2, 3> qppq; \
    detail::ivector_swizzle4<4, 3, 2, 3, 0> qpqs; \
    detail::ivector_swizzle4<4, 3, 2, 3, 1> qpqt; \
    detail::ivector_swizzle4<4, 3, 2, 3, 2> qpqp; \
    detail::ivector_swizzle4<4, 3, 2, 3, 3> qpqq; \
    detail::ivector_swizzle4<4, 3, 3, 0, 0> qqss; \
    detail::ivector_swizzle4<4, 3, 3, 0, 1> qqst; \
    detail::ivector_swizzle4<4, 3, 3, 0, 2> qqsp; \
    detail::ivector_swizzle4<4, 3, 3, 0, 3> qqsq; \
    detail::ivector_swizzle4<4, 3, 3, 1, 0> qqts; \
    detail::ivector_swizzle4<4, 3, 3, 1, 1> qqtt; \
    detail::ivector_swizzle4<4, 3, 3, 1, 2> qqtp; \
    detail::ivector_swizzle4<4, 3, 3, 1, 3> qqtq; \
    detail::ivector_swizzle4<4, 3, 3, 2, 0> qqps; \
    detail::ivector_swizzle4<4, 3, 3, 2, 1> qqpt; \
    detail::ivector_swizzle4<4, 3, 3, 2, 2> qqpp; \
    detail::ivector_swizzle4<4, 3, 3, 2, 3> qqpq; \
    detail::ivector_swizzle4<4, 3, 3, 3, 0> qqqs; \
    detail::ivector_swizzle4<4, 3, 3, 3, 1> qqqt; \
    detail::ivector_swizzle4<4, 3, 3, 3, 2> qqqp; \
    detail::ivector_swizzle4<4, 3, 3, 3, 3> qqqq; \
    /* end generated int4 swizzles */
