//
// GeneratedUint2Swizzles.h - generated-style public uint2 swizzle declarations
//
// This file is generated by tools/gen_vector_swizzles.py.
// Do not hand-edit the swizzle list.
//

#pragma once

#define CHLM_DETAIL_DECLARE_UINT2_SWIZZLES() \
    /* xy family */ \
    /* xy length 2 */ \
    detail::uvector_swizzle2<2, 0, 0> xx; \
    detail::uvector_swizzle2<2, 0, 1> xy; \
    detail::uvector_swizzle2<2, 1, 0> yx; \
    detail::uvector_swizzle2<2, 1, 1> yy; \
    /* xy length 3 */ \
    detail::uvector_swizzle3<2, 0, 0, 0> xxx; \
    detail::uvector_swizzle3<2, 0, 0, 1> xxy; \
    detail::uvector_swizzle3<2, 0, 1, 0> xyx; \
    detail::uvector_swizzle3<2, 0, 1, 1> xyy; \
    detail::uvector_swizzle3<2, 1, 0, 0> yxx; \
    detail::uvector_swizzle3<2, 1, 0, 1> yxy; \
    detail::uvector_swizzle3<2, 1, 1, 0> yyx; \
    detail::uvector_swizzle3<2, 1, 1, 1> yyy; \
    /* xy length 4 */ \
    detail::uvector_swizzle4<2, 0, 0, 0, 0> xxxx; \
    detail::uvector_swizzle4<2, 0, 0, 0, 1> xxxy; \
    detail::uvector_swizzle4<2, 0, 0, 1, 0> xxyx; \
    detail::uvector_swizzle4<2, 0, 0, 1, 1> xxyy; \
    detail::uvector_swizzle4<2, 0, 1, 0, 0> xyxx; \
    detail::uvector_swizzle4<2, 0, 1, 0, 1> xyxy; \
    detail::uvector_swizzle4<2, 0, 1, 1, 0> xyyx; \
    detail::uvector_swizzle4<2, 0, 1, 1, 1> xyyy; \
    detail::uvector_swizzle4<2, 1, 0, 0, 0> yxxx; \
    detail::uvector_swizzle4<2, 1, 0, 0, 1> yxxy; \
    detail::uvector_swizzle4<2, 1, 0, 1, 0> yxyx; \
    detail::uvector_swizzle4<2, 1, 0, 1, 1> yxyy; \
    detail::uvector_swizzle4<2, 1, 1, 0, 0> yyxx; \
    detail::uvector_swizzle4<2, 1, 1, 0, 1> yyxy; \
    detail::uvector_swizzle4<2, 1, 1, 1, 0> yyyx; \
    detail::uvector_swizzle4<2, 1, 1, 1, 1> yyyy; \
    /* rg family */ \
    /* rg length 2 */ \
    detail::uvector_swizzle2<2, 0, 0> rr; \
    detail::uvector_swizzle2<2, 0, 1> rg; \
    detail::uvector_swizzle2<2, 1, 0> gr; \
    detail::uvector_swizzle2<2, 1, 1> gg; \
    /* rg length 3 */ \
    detail::uvector_swizzle3<2, 0, 0, 0> rrr; \
    detail::uvector_swizzle3<2, 0, 0, 1> rrg; \
    detail::uvector_swizzle3<2, 0, 1, 0> rgr; \
    detail::uvector_swizzle3<2, 0, 1, 1> rgg; \
    detail::uvector_swizzle3<2, 1, 0, 0> grr; \
    detail::uvector_swizzle3<2, 1, 0, 1> grg; \
    detail::uvector_swizzle3<2, 1, 1, 0> ggr; \
    detail::uvector_swizzle3<2, 1, 1, 1> ggg; \
    /* rg length 4 */ \
    detail::uvector_swizzle4<2, 0, 0, 0, 0> rrrr; \
    detail::uvector_swizzle4<2, 0, 0, 0, 1> rrrg; \
    detail::uvector_swizzle4<2, 0, 0, 1, 0> rrgr; \
    detail::uvector_swizzle4<2, 0, 0, 1, 1> rrgg; \
    detail::uvector_swizzle4<2, 0, 1, 0, 0> rgrr; \
    detail::uvector_swizzle4<2, 0, 1, 0, 1> rgrg; \
    detail::uvector_swizzle4<2, 0, 1, 1, 0> rggr; \
    detail::uvector_swizzle4<2, 0, 1, 1, 1> rggg; \
    detail::uvector_swizzle4<2, 1, 0, 0, 0> grrr; \
    detail::uvector_swizzle4<2, 1, 0, 0, 1> grrg; \
    detail::uvector_swizzle4<2, 1, 0, 1, 0> grgr; \
    detail::uvector_swizzle4<2, 1, 0, 1, 1> grgg; \
    detail::uvector_swizzle4<2, 1, 1, 0, 0> ggrr; \
    detail::uvector_swizzle4<2, 1, 1, 0, 1> ggrg; \
    detail::uvector_swizzle4<2, 1, 1, 1, 0> gggr; \
    detail::uvector_swizzle4<2, 1, 1, 1, 1> gggg; \
    /* st family */ \
    /* st length 2 */ \
    detail::uvector_swizzle2<2, 0, 0> ss; \
    detail::uvector_swizzle2<2, 0, 1> st; \
    detail::uvector_swizzle2<2, 1, 0> ts; \
    detail::uvector_swizzle2<2, 1, 1> tt; \
    /* st length 3 */ \
    detail::uvector_swizzle3<2, 0, 0, 0> sss; \
    detail::uvector_swizzle3<2, 0, 0, 1> sst; \
    detail::uvector_swizzle3<2, 0, 1, 0> sts; \
    detail::uvector_swizzle3<2, 0, 1, 1> stt; \
    detail::uvector_swizzle3<2, 1, 0, 0> tss; \
    detail::uvector_swizzle3<2, 1, 0, 1> tst; \
    detail::uvector_swizzle3<2, 1, 1, 0> tts; \
    detail::uvector_swizzle3<2, 1, 1, 1> ttt; \
    /* st length 4 */ \
    detail::uvector_swizzle4<2, 0, 0, 0, 0> ssss; \
    detail::uvector_swizzle4<2, 0, 0, 0, 1> ssst; \
    detail::uvector_swizzle4<2, 0, 0, 1, 0> ssts; \
    detail::uvector_swizzle4<2, 0, 0, 1, 1> sstt; \
    detail::uvector_swizzle4<2, 0, 1, 0, 0> stss; \
    detail::uvector_swizzle4<2, 0, 1, 0, 1> stst; \
    detail::uvector_swizzle4<2, 0, 1, 1, 0> stts; \
    detail::uvector_swizzle4<2, 0, 1, 1, 1> sttt; \
    detail::uvector_swizzle4<2, 1, 0, 0, 0> tsss; \
    detail::uvector_swizzle4<2, 1, 0, 0, 1> tsst; \
    detail::uvector_swizzle4<2, 1, 0, 1, 0> tsts; \
    detail::uvector_swizzle4<2, 1, 0, 1, 1> tstt; \
    detail::uvector_swizzle4<2, 1, 1, 0, 0> ttss; \
    detail::uvector_swizzle4<2, 1, 1, 0, 1> ttst; \
    detail::uvector_swizzle4<2, 1, 1, 1, 0> ttts; \
    detail::uvector_swizzle4<2, 1, 1, 1, 1> tttt; \
    /* uv family */ \
    /* uv length 2 */ \
    detail::uvector_swizzle2<2, 0, 0> uu; \
    detail::uvector_swizzle2<2, 0, 1> uv; \
    detail::uvector_swizzle2<2, 1, 0> vu; \
    detail::uvector_swizzle2<2, 1, 1> vv; \
    /* uv length 3 */ \
    detail::uvector_swizzle3<2, 0, 0, 0> uuu; \
    detail::uvector_swizzle3<2, 0, 0, 1> uuv; \
    detail::uvector_swizzle3<2, 0, 1, 0> uvu; \
    detail::uvector_swizzle3<2, 0, 1, 1> uvv; \
    detail::uvector_swizzle3<2, 1, 0, 0> vuu; \
    detail::uvector_swizzle3<2, 1, 0, 1> vuv; \
    detail::uvector_swizzle3<2, 1, 1, 0> vvu; \
    detail::uvector_swizzle3<2, 1, 1, 1> vvv; \
    /* uv length 4 */ \
    detail::uvector_swizzle4<2, 0, 0, 0, 0> uuuu; \
    detail::uvector_swizzle4<2, 0, 0, 0, 1> uuuv; \
    detail::uvector_swizzle4<2, 0, 0, 1, 0> uuvu; \
    detail::uvector_swizzle4<2, 0, 0, 1, 1> uuvv; \
    detail::uvector_swizzle4<2, 0, 1, 0, 0> uvuu; \
    detail::uvector_swizzle4<2, 0, 1, 0, 1> uvuv; \
    detail::uvector_swizzle4<2, 0, 1, 1, 0> uvvu; \
    detail::uvector_swizzle4<2, 0, 1, 1, 1> uvvv; \
    detail::uvector_swizzle4<2, 1, 0, 0, 0> vuuu; \
    detail::uvector_swizzle4<2, 1, 0, 0, 1> vuuv; \
    detail::uvector_swizzle4<2, 1, 0, 1, 0> vuvu; \
    detail::uvector_swizzle4<2, 1, 0, 1, 1> vuvv; \
    detail::uvector_swizzle4<2, 1, 1, 0, 0> vvuu; \
    detail::uvector_swizzle4<2, 1, 1, 0, 1> vvuv; \
    detail::uvector_swizzle4<2, 1, 1, 1, 0> vvvu; \
    detail::uvector_swizzle4<2, 1, 1, 1, 1> vvvv; \
    /* end generated uint2 swizzles */
