#!/usr/bin/env python3
#
# Created by Zack Shrout on 7/12/26.
# Copyright (c) 2026 BunnySoft. All rights reserved.
#
"""
Generate the public float vector swizzle declaration headers.

This is a maintainer tool. Library consumers should never need to run it.
"""

from itertools import product
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "include" / "chlm" / "detail"

VECTOR_CONFIGS = [
    {
        "components": 2,
        "macro": "CHLM_DETAIL_DECLARE_FLOAT2_SWIZZLES",
        "filename": "GeneratedFloat2Swizzles.h",
        "type_prefix": "float",
        "swizzle_prefix": "vector_swizzle",
        "families": [
            ("xy", "xy"),
            ("rg", "rg"),
            ("st", "st"),
            ("uv", "uv"),
        ],
    },
    {
        "components": 3,
        "macro": "CHLM_DETAIL_DECLARE_FLOAT3_SWIZZLES",
        "filename": "GeneratedFloat3Swizzles.h",
        "type_prefix": "float",
        "swizzle_prefix": "vector_swizzle",
        "families": [
            ("xyz", "xyz"),
            ("rgb", "rgb"),
            ("stp", "stp"),
        ],
    },
    {
        "components": 2,
        "macro": "CHLM_DETAIL_DECLARE_INT2_SWIZZLES",
        "filename": "GeneratedInt2Swizzles.h",
        "type_prefix": "int",
        "swizzle_prefix": "ivector_swizzle",
        "families": [
            ("xy", "xy"),
            ("rg", "rg"),
            ("st", "st"),
            ("uv", "uv"),
        ],
    },
    {
        "components": 3,
        "macro": "CHLM_DETAIL_DECLARE_INT3_SWIZZLES",
        "filename": "GeneratedInt3Swizzles.h",
        "type_prefix": "int",
        "swizzle_prefix": "ivector_swizzle",
        "families": [
            ("xyz", "xyz"),
            ("rgb", "rgb"),
            ("stp", "stp"),
        ],
    },
    {
        "components": 4,
        "macro": "CHLM_DETAIL_DECLARE_INT4_SWIZZLES",
        "filename": "GeneratedInt4Swizzles.h",
        "type_prefix": "int",
        "swizzle_prefix": "ivector_swizzle",
        "families": [
            ("xyzw", "xyzw"),
            ("rgba", "rgba"),
            ("stpq", "stpq"),
        ],
    },
    {
        "components": 2,
        "macro": "CHLM_DETAIL_DECLARE_UINT2_SWIZZLES",
        "filename": "GeneratedUint2Swizzles.h",
        "type_prefix": "uint",
        "swizzle_prefix": "uvector_swizzle",
        "families": [
            ("xy", "xy"),
            ("rg", "rg"),
            ("st", "st"),
            ("uv", "uv"),
        ],
    },
    {
        "components": 3,
        "macro": "CHLM_DETAIL_DECLARE_UINT3_SWIZZLES",
        "filename": "GeneratedUint3Swizzles.h",
        "type_prefix": "uint",
        "swizzle_prefix": "uvector_swizzle",
        "families": [
            ("xyz", "xyz"),
            ("rgb", "rgb"),
            ("stp", "stp"),
        ],
    },
    {
        "components": 4,
        "macro": "CHLM_DETAIL_DECLARE_UINT4_SWIZZLES",
        "filename": "GeneratedUint4Swizzles.h",
        "type_prefix": "uint",
        "swizzle_prefix": "uvector_swizzle",
        "families": [
            ("xyzw", "xyzw"),
            ("rgba", "rgba"),
            ("stpq", "stpq"),
        ],
    },
    {
        "components": 4,
        "macro": "CHLM_DETAIL_DECLARE_FLOAT4_SWIZZLES",
        "filename": "GeneratedFloat4Swizzles.h",
        "type_prefix": "float",
        "swizzle_prefix": "vector_swizzle",
        "families": [
            ("xyzw", "xyzw"),
            ("rgba", "rgba"),
            ("stpq", "stpq"),
        ],
    },
]


def emit_family(components: int, symbols: str, swizzle_prefix: str) -> list[str]:
    lines: list[str] = []
    for length in range(2, 5):
        lines.append(f"    /* {symbols} length {length} */ \\")
        for indices in product(range(components), repeat=length):
            name = "".join(symbols[index] for index in indices)
            template_args = ", ".join(str(index) for index in indices)
            lines.append(
                f"    detail::{swizzle_prefix}{length}<{components}, {template_args}> {name}; \\"
            )
    return lines


def emit_header(
    components: int,
    macro: str,
    filename: str,
    families: list[tuple[str, str]],
    type_prefix: str,
    swizzle_prefix: str,
) -> str:
    lines = [
        "//",
        f"// {filename} - generated-style public {type_prefix}{components} swizzle declarations",
        "//",
        "// This file is generated by tools/gen_vector_swizzles.py.",
        "// Do not hand-edit the swizzle list.",
        "//",
        "",
        "#pragma once",
        "",
        f"#define {macro}() \\",
    ]

    for family_name, symbols in families:
        lines.append(f"    /* {family_name} family */ \\")
        lines.extend(emit_family(components, symbols, swizzle_prefix))

    lines.append(f"    /* end generated {type_prefix}{components} swizzles */")
    return "\n".join(lines) + "\n"


def main() -> None:
    for config in VECTOR_CONFIGS:
        output = OUTPUT_DIR / config["filename"]
        output.write_text(
            emit_header(
                config["components"],
                config["macro"],
                config["filename"],
                config["families"],
                config["type_prefix"],
                config["swizzle_prefix"],
            ),
            encoding="utf-8",
        )


if __name__ == "__main__":
    main()
